### ISSUE TITLE
Logo is missing

### ISSUE THREAD

**Issue by trymoto** [iamolegga/nestjs-pino#1]
Okay, so i think this project can better communicate its value through some visuals.

**Comment by trymoto** [comment]
So i've been thinking about it: NestJS, Pino – what their perfect marriage could look like? Pino has some fine and refreshing pine tree texture and warmth. Nest is all about sweet furriness of cats and such.

![p-01](https://user-images.githubusercontent.com/2513899/65182079-26ddc480-da69-11e9-856b-31695f8e4a45.png)

**Comment by trymoto** [comment]
Quite naturally, this comes to my mind:

![p-02](https://user-images.githubusercontent.com/2513899/65182121-407f0c00-da69-11e9-8b47-890e8be4a318.png)

Let me tell you why i think this is the best logo this project could ever have:
- has a cat
- has some nice pino pine trees in the background
- has lasers coming out of cat's eyes
- it shows both immense power of this tool and it's seamless integration with both technologies!

**Comment by iamolegga** [comment]
This is it. Closing. Please, open PR to add it
