### ISSUE TITLE
[QUESTION]: How to use the logger to log graphQL queries

### ISSUE THREAD

**Issue by rubiin** [iamolegga/nestjs-pino#1002]
For rest apis, the logger seems to be working fine. However in graphql, i cannot seem to hook it so as to log the queries

[x] I've read [the docs of nestjs-pino](https://github.com/iamolegga/nestjs-pino/blob/master/README.md)

[x] I've read [the docs of pino](https://getpino.io/#/)

[x] I couldn't find the same [question about nestjs-pino](https://github.com/iamolegga/nestjs-pino/issues?q=label%3Aquestion)

**Question**

**Please mention other relevant information such as Node.js version and Operating System.**

**Comment by iamolegga** [comment]
1 read this https://docs.nestjs.com/graphql/plugins

2 read this https://www.apollographql.com/docs/apollo-server/integrations/plugins/

3 implement something like this, but with your desired details:

```ts
import { Logger } from '@nestjs/common';
import { Plugin } from '@nestjs/graphql';
import { GraphQLRequestContext } from 'apollo-server-core';
import {
  ApolloServerPlugin,
  GraphQLRequestListener,
  GraphQLRequestContextDidEncounterErrors,
} from 'apollo-server-plugin-base';

@Plugin()
export class GraphQLLogger implements ApolloServerPlugin {
  private readonly logger = new Logger(GraphQLLogger.name);

  async requestDidStart(
    startCtx: GraphQLRequestContext,
  ): Promise<GraphQLRequestListener> {
    return new Listener(
      {
        query: startCtx.request.query,
        operationName: startCtx.request.operationName,
      },
      this.logger,
      // bad bad bad bad typings in lib
    ) as unknown as GraphQLRequestListener;
  }
}

class Listener<T = unknown>
  // bad bad bad bad typings in lib
  implements
    Pick<GraphQLRequestListener<T>, 'didEncounterErrors' | 'willSendResponse'>
{
  private readonly start: number;

  constructor(
    private readonly logData: Record<string, unknown>,
    private readonly logger: Logger,
  ) {
    this.start = Date.now();
  }

  async didEncounterErrors(
    errorsCtx: GraphQLRequestContextDidEncounterErrors<T>,
  ): Promise<void> {
    this.logData.errors = errorsCtx.errors;
  }

  async willSendResponse(): Promise<void> {
    this.logger.log(
      {
        graphql: this.logData,
        responseTime: Date.now() - this.start,
      },
      this.logData.errors ? 'request errored' : 'request completed',
    );
  }
}

```

4 optionally disable default logging for graphql path in logger config to exclude duplicates:

```ts
  autoLogging: {
    ignorePaths: [
      // gql has it's own logger
      '/graphql',
    ],
  },
```

Does it help?

**Comment by rubiin** [comment]
![](https://i.imgur.com/BbQ5B7N.png)

I am getting logs lie this. Is this supposed to happen.

**Comment by iamolegga** [comment]
It's up to you what you want to log, just change what you pass in `requestDidStart` to `new Listener`. I believe this can be closed, for more details read the docs, please
