### ISSUE TITLE
Add support for pino-http@8.x

### ISSUE THREAD

**Issue by NoNameProvided** [iamolegga/nestjs-pino#1008]
**Is your feature request related to a problem? Please describe.**
I would like to use this lib with the latest pino-http package.

**Describe the solution you'd like**
The `nestjs-pino` package supports pino-http@8.

**Additional context**
There seems to be no breaking change neither in pino@8 and pino-http@8 release.

**Comment by iamolegga** [comment]
there is an open pr for this #995 but test didn't pass. I haven't much time to fix that unfortunately. Also if there are not any breaking changes the peer deps versions should be set keeping previous version

**Comment by NoNameProvided** [comment]
> Also if there are not any breaking changes the peer deps versions should be set keeping previous version 

I don't understand this bit. Currently `nestjs-pino` has "pino-http" defined as peer-dependency with "^6.4.0 || ^7.0.0". This means the newer NPM versions refuse to install `pino-http@8` because this package doesn't allow `8.x` (this is quite a recent change in NPM, I think it's only in the latest major version).

**Comment by iamolegga** [comment]
I mean keep previous versions and add the new one. ^6.4.0 || ^7.0.0 || ^8.0.0

**Comment by 0xslipk** [comment]
> there is an open pr for this #995 but test didn't pass. I haven't much time to fix that unfortunately. Also if there are not any breaking changes the peer deps versions should be set keeping previous version

I will fix the PR this weekend. Sorry I didn't have much time

**Comment by iamolegga** [comment]
released in v3.0.0
