### ISSUE TITLE
[BUG] PinoLogger: unable to assign extra fields out of request scope // when trying to assign from middleware

### ISSUE THREAD

**Issue by schealex** [iamolegga/nestjs-pino#1021]
[x] I've read [the docs of nestjs-pino](https://github.com/iamolegga/nestjs-pino/blob/master/README.md)

[x] I've read [the docs of pino](https://getpino.io/#/)

[x] I couldn't find the same [open issue of nestjs-pino](https://github.com/iamolegga/nestjs-pino/issues)

**What is the current behavior?**
When trying to use `logger.assign` you receive the error "PinoLogger: unable to assign extra fields out of request scope"

```
{"level":30,"time":1657116598814,"pid":908,"hostname":"ascherer-pc","context":"NestFactory","msg":"Starting Nest application..."}
{"level":30,"time":1657116598815,"pid":908,"hostname":"ascherer-pc","context":"InstanceLoader","msg":"AppModule dependencies initialized"}    
{"level":30,"time":1657116598815,"pid":908,"hostname":"ascherer-pc","context":"InstanceLoader","msg":"LoggerModule dependencies initialized"} 
{"level":30,"time":1657116598815,"pid":908,"hostname":"ascherer-pc","context":"RoutesResolver","msg":"AppController {/}:"}
{"level":30,"time":1657116598815,"pid":908,"hostname":"ascherer-pc","context":"RouterExplorer","msg":"Mapped {/, GET} route"}
{"level":30,"time":1657116598815,"pid":908,"hostname":"ascherer-pc","context":"NestApplication","msg":"Nest application successfully started"}
{"level":50,"time":1657116608244,"pid":908,"hostname":"ascherer-pc","context":"ExceptionsHandler","err":{"type":"Error","message":"PinoLogger: unable to assign extra fields out of request scope","stack":"Error: PinoLogger: unable to assign extra fields out of request scope\n    at PinoLogger.assign (C:\\dev\\github.com\\nestjs-pino-request-scope-examp
le\\node_modules\\nestjs-pino\\PinoLogger.js:104:19)\n    at LoggerContextMiddleware.use (C:\\dev\\github.com\\nestjs-pino-request-scope-example\\src\\logger-context.middleware.ts:12:17)\n    at C:\\dev\\github.com\\nestjs-pino-request-scope-example\\node_modules\\@nestjs\\core\\router\\router-proxy.js:9:23\n    at Layer.handle [as handle_request] (C:
\\dev\\github.com\\nestjs-pino-request-scope-example\\node_modules\\express\\lib\\router\\layer.js:95:5)\n    at trim_prefix (C:\\dev\\github.com\\nestjs-pino-request-scope-example\\node_modules\\express\\lib\\router\\index.js:328:13)\n    at C:\\dev\\github.com\\nestjs-pino-request-scope-example\\node_modules\\express\\lib\\router\\index.js:286:9\n  
  at param (C:\\dev\\github.com\\nestjs-pino-request-scope-example\\node_modules\\express\\lib\\router\\index.js:365:14)\n    at param (C:\\dev\\github.com\\nestjs-pino-request-scope-example\\node_modules\\express\\lib\\router\\index.js:376:14)\n    at Function.process_params (C:\\dev\\github.com\\nestjs-pino-request-scope-example\\node_modules\\expre
ss\\lib\\router\\index.js:421:3)\n    at next (C:\\dev\\github.com\\nestjs-pino-request-scope-example\\node_modules\\express\\lib\\router\\index.js:280:10)"},"msg":"PinoLogger: unable to assign extra fields out of request scope"}

```

**What is the expected behavior?**
The specified value get's assigned for the logs of the current request

**Please provide minimal example repo. Without it this issue will be closed**
https://github.com/schealex/nestjs-pino-request-scope-example

**Please mention other relevant information such as Node.js version and Operating System.**
this is the bug report follow up for my question https://github.com/iamolegga/nestjs-pino/issues/1020

**Comment by schealex** [comment]
@iamolegga sorry but do you have any idea what the cause of this could be? This is severly hindering our development right now :/ i've tried a couple workarounds but nothing seems to able to make this work the way we need it to

**Comment by iamolegga** [comment]
Sorry, don't have time to check this at the moment, maybe you can try to move this assigning from middleware to interceptor? Also, did you check that in example middlewares are in the right order and your middleware goes after lib's one? Can you try to create one more module with middleware consumer and add it as a dependency for AppModule instead of adding middleware directly in `AppModule`?

**Comment by schealex** [comment]
No worries that was already very helpful!

I've created two new branches on my test repo:

- moved the middleware to it's own module (same error): https://github.com/schealex/nestjs-pino-request-scope-example/tree/feature/move-middleware-to-own-module
- move the assign to a interceptor (which works!): https://github.com/schealex/nestjs-pino-request-scope-example/tree/feature/using-interceptor

hope this can help you resolve this. At least for our case i can go the interceptor route now :) thanks!

**Comment by CatsMiaow** [comment]
You need to detach the `LoggerModule` from the `LoggerContextModule` from the [example where you get the same error](https://github.com/schealex/nestjs-pino-request-scope-example/blob/feature/move-middleware-to-own-module/src/logger-context.module.ts).
If placed in the same module, `LoggerContextMiddleware` will be applied first.

```ts
@Module({
  imports: [
    LoggerModule.forRoot(),
    LoggerContextModule,
  ],
})
export class AppModule {}
```
> https://github.com/CatsMiaow/node-nestjs-structure/blob/master/src/common/common.module.ts#L13-L18

This solves the issue, but there is another problem.
The same error occurs when accessing the path excluded by the logger.
> https://github.com/CatsMiaow/node-nestjs-structure/blob/master/src/config/logger.config.ts#L25-L28

The above problem requires checking the `storage` of `nestjs-pino` in `LoggerContextMiddleware`.
> https://github.com/CatsMiaow/node-nestjs-structure/blob/master/src/common/middleware/logger-context.middleware.ts#L15-L21

It would be nice if I could solve the problem without accessing `nestjs-pino/storage`.

**Comment by CatsMiaow** [comment]
thanks, changed `exclude` to `autoLogging.ignore` and removed the `storage` check.
> https://github.com/CatsMiaow/node-nestjs-structure/blob/master/src/config/logger.config.ts#L21-L23

**Comment by iamolegga** [comment]
So, this is not a bug, right? Does anyone would like to add a test for this?
