### ISSUE TITLE
[QUESTION] How to use Logger in Submodule from library package?

### ISSUE THREAD

**Issue by schealex** [iamolegga/nestjs-pino#1028]
[x] I've read [the docs of nestjs-pino](https://github.com/iamolegga/nestjs-pino/blob/master/README.md)

[x] I've read [the docs of pino](https://getpino.io/#/)

[x] I couldn't find the same [question about nestjs-pino](https://github.com/iamolegga/nestjs-pino/issues?q=label%3Aquestion)

**Question**
In our use case we have multiple micoservices each of which has it's own client libary. We would like to use the logger in our primary micoservice and in the client libaries which get used by the microservices. Sadly right now i cannot get this to work because the PinoLogger instance is not found and I have to add the PinoLogger to the providers which leads to it being a new (different) instance.

Please let me know if i need to explain this a little more.

Strukture looks like this:

Microservice
> Imports LoggerModule
> uses SomeOtherServiceClientModule
>> uses InjectPinoLogger to try to log to the same instance

here are some snippets:

Microservice app.module.ts
```ts
export const tdsLoggerOptions: TdsLoggerOptions = {
  appName: name,
  appVersion: version,
  prettyPrint: false, // DO NOT use true for deployments!
};

@Module({
  imports: [
    HealthModule,
    LoggerModule.forRoot(createPinoHttpOptions(tdsLoggerOptions)),
    ServiceClientModule.forRoot({xxx}), // this is a client module from a library
    ConfigModule.forRoot({
      isGlobal: true,
      load: [configuration],
    }),
    AutomapperModule.forRoot({
      strategyInitializer: sequelize(),
    }),
    SequelizeModule.forRootAsync({xxx}),
    SomeModule,
    SomeOtherModule,
  ],
  controllers: [],
  providers: [],
})
export class AppModule {}
```

ServiceClientModule.module.ts

```ts
@Global()
@Module({})
export class ServiceClientModule{
  static forRoot(options: ServiceClientModuleOptions): DynamicModule {
    const optionsWithDefaults = Object.assign(
      {},
      defaultClientOptions,
      options,
    );

    const providers: any = [
      ServiceClientService,
      {
        provide: SERVICE_CLIENT_OPTIONS,
        useValue: optionsWithDefaults,
      },
      {
        provide: APP_GUARD,
        useClass: AuthGuard,
      },
    ];

    if (optionsWithDefaults.usePermissions)
      providers.push({
        provide: APP_GUARD,
        useClass: PermissionsGuard,
      });

    return {
      imports: [RequestContextModule, HttpModule, PinoLogger],
      module: ServiceClientModule,
      providers: [
        Reflector,
        ServiceClientService,
        ...providers,
      ],
      exports: [
        {
          provide: SERVICE_CLIENT_OPTIONS,
          useValue: optionsWithDefaults,
        },
        ServiceClientService
      ],
    };
  }
}
```

ServiceClientModuleService (serviceclient.service.ts)
```ts
@Injectable()
export class ServiceClientService{
  private tokenStore: TokenStore;

  constructor(
    @Inject(SERVICE_CLIENT_OPTIONS)
    private options: ServiceClientModuleOptions,
    private httpService: HttpService,

    @InjectPinoLogger(ServiceClientService.name)
    private readonly logger: PinoLogger, // this logger is not the same instance as the one from the microservice created by (LoggerModule.forRoot)
  ) {
    this.tokenStore = new TokenStore();
  }
}
```

**Please mention other relevant information such as Node.js version and Operating System.**

**Comment by schealex** [comment]
I was afraid of that :D

so based on my last question and error report: https://github.com/iamolegga/nestjs-pino/issues/1021
i was going to add a interceptor to our authentification client but the authentification client needs to receive the same logger instance otherwise if you use the logger or even logger.assign it would not have an effect on logs that are done by the service itself.

Basically it seems like if you:

- create nestjs app importing the LoggerModule
- create a nestjs library with a module that requires the PinoLogger instance

i'm unable to affect the instance of the nestjs app via the nestjs libary :/

**Comment by iamolegga** [comment]
Basically you need PinoLogger only in place when you assign properies. In all the other places just use standard logger from nest/common
