### ISSUE TITLE
Default asynchronous logging configuration

### ISSUE THREAD

**Issue by jhonatasobrinho** [iamolegga/nestjs-pino#1031]
- [x] I've read [the docs of nestjs-pino](https://github.com/iamolegga/nestjs-pino/blob/master/README.md)
- [x] I've read [the docs of pino](https://getpino.io/#/)
- [x] I couldn't find the same [question about nestjs-pino](https://github.com/iamolegga/nestjs-pino/issues?q=label%3Aquestion)

**Question**
I looked into the [`nestjs-pino`](https://github.com/iamolegga/nestjs-pino#asynchronous-logging) docs and the [`pinojs`](https://github.com/pinojs/pino/blob/master/docs/api.md#pino-destination) docs and both differ from what is correct about the defaut configuration over sync/async logging.

Based on `pinojs` it should be `sync: false` by default, but based on `nestjs-pino` documentation, it is `sync: true` the default. 
I made a research on the code and nestjs-pino doesn't modify the defaults on pinoHttp object.

Can someone confirm the default configuration for this property, please?

The documentation was modified last time on the merge of the #907.

**Comment by iamolegga** [comment]
Not sure if this is related to this lib. nestjs-pino just pass pino-http config to pino-http library. That's it. All the settings are up to you.

> based on nestjs-pino documentation, it is sync: true the default

[default](https://github.com/iamolegga/nestjs-pino#zero-configuration) is pino instance without config.
