### ISSUE TITLE
Post-install small typo

### ISSUE THREAD

**Issue by exsesx** [iamolegga/nestjs-pino#1042]
Hi!

I've noticed this small typo in the post-install script.

Now you know.

https://github.com/iamolegga/nestjs-pino/blob/246847e2bc77429a11a3ac38da6170c9ccc60c2c/postinstall.js#L8

I'm from Ukraine btw 🇺🇦

**Comment by exsesx** [comment]
I've attached PR to fix this.

**Comment by iamolegga** [comment]
![image](https://user-images.githubusercontent.com/5501657/180167430-e639f64d-d5e9-4d0b-99af-dc88fcb0ebc4.png)


I must be sleepy when wrote this 🤦‍♂️🤦‍♂️🤦‍♂️

Дякую, слава Украïнi!
