### ISSUE TITLE
[QUESTION] Access to Request Context

### ISSUE THREAD

**Issue by sethtomy** [iamolegga/nestjs-pino#1044]
[x] I've read [the docs of nestjs-pino](https://github.com/iamolegga/nestjs-pino/blob/master/README.md)

[x] I've read [the docs of pino](https://getpino.io/#/)

[x] I couldn't find the same [question about nestjs-pino](https://github.com/iamolegga/nestjs-pino/issues?q=label%3Aquestion)

**Question**

Disclaimer: I found similar questions in #314 and #164 but ideally would like to get the data from AsyncLocalStorage.

I'm trying to get request context data out of the logger to use with subsequent http requests. In my particular use case I'd like to get the "x-correlation-id" header from the request context.

Is this possible using this library?

**Please mention other relevant information such as Node.js version and Operating System.**

**Comment by iamolegga** [comment]
I'm not sure that this is a good idea to use logger as a wrapper for passing metadata between app layers, but as a dirty hack yes it's possible.

You have to inject `PinoLogger`, it has [logger](https://github.com/iamolegga/nestjs-pino/blob/master/src/PinoLogger.ts#L137-L141) field of pino type. With pino instance you can get it's `.bindings()`, which has by default fields that you need: `{ req: { id, ... }, ... }`. So you just have to set config for this module properly, for example:

```ts
  genReqId: (req) => {
    return req.headers['x-request-id'];
  },
```

I believe we can add it to FAQ section, as I'm sure there were similar question before
