### ISSUE TITLE
[QUESTION] Override error message

### ISSUE THREAD

**Issue by EcksDy** [iamolegga/nestjs-pino#1057]
[V] I've read [the docs of nestjs-pino](https://github.com/iamolegga/nestjs-pino/blob/master/README.md)

[V] I've read [the docs of pino](https://getpino.io/#/)

[V] I couldn't find the same [question about nestjs-pino](https://github.com/iamolegga/nestjs-pino/issues?q=label%3Aquestion)

**Question**

Hello,

I'm implementing an adapter that will align our internal logging conventions to nestjs-pino api.  
Our error messages are looking as follows:
```typescript
catch (error) {
  this.logger.error('Custom error message', error);
  this.logger.error('Custom error message with context', { error, someExtraContext });
}
```

Is there a way I can manipulate this input to achieve the following behaviour:
- Take the provided custom message and have it as the message in the output json
- Preserve the whole error information including stack trace and message, inside err object

Currently in the adapter I manipulate the input into something along the lines of:
```typescript
  error(message: string, context: unknown): void {
    if (context instanceof Error) {
      const error = context;
      this.logger.error(error, { message }); // The logger used here is `import { Logger } from 'nestjs-pino';`
      return;
    }

    const { error, ...cleanContext } = context as any;
    this.logger.error(error, { message, ...cleanContext }); // The logger used here is `import { Logger } from 'nestjs-pino';`
  }
```

All my attempts ended up either losing the error information or being unable to override the message of the output log, as the message on the error object takes precedence.

At this point I'm not sure if this is possible, would love to hear your thoughts, thank you!

**Comment by iamolegga** [comment]
Didn't get what do you mean by "adapter".

First of all `this.logger.error('Custom error message with context', { error, someExtraContext });` does not match with the pino's message format: [`logger.error([mergingObject], [message], [...interpolationValues]`](https://getpino.io/#/docs/api?id=logging-method-parameters)

Second, it has [LoggerErrorInterceptor which logs stack trace](https://github.com/iamolegga/nestjs-pino#expose-stack-trace-and-error-class-in-err-property)

Third, for pino to log errors properly it should be passed as `.err` filed on merging object. Read [this](https://getpino.io/#/docs/api?id=logging-method-parameters).

Fourth, pino has [serializers](https://getpino.io/#/docs/api?id=serializers-object) options.

I hope something of this will help, closing
