### ISSUE TITLE
[BUG] Not Work IN Repl Mode In  NESTJS 9~  

### ISSUE THREAD

**Issue by Leizhenpeng** [iamolegga/nestjs-pino#1084]
- [x]  I've read [the docs of nestjs-pino](https://github.com/iamolegga/nestjs-pino/blob/master/README.md)

- [x] I've read [the docs of pino](https://getpino.io/#/)

- [x] I couldn't find the same [open issue of nestjs-pino](https://github.com/iamolegga/nestjs-pino/issues)

**What is the current behavior?**

> if open repl mode , NestJS standard built-in logger still will work ~

<img width="951" alt="image" src="https://user-images.githubusercontent.com/50035229/184574037-d8fbe4cf-b987-4350-b253-3db32cbdecde.png">

**What is the expected behavior?**
Logs will be produced by pino internally

**Please provide minimal example repo. Without it this issue will be closed**
[example](https://github.com/Leizhenpeng/nestjs-pino/tree/master/example)
**Please mention other relevant information such as Node.js version and Operating System.**

**Comment by iamolegga** [comment]
@Leizhenpeng is this a limitation of nestjs and this doesn't work with other loggers or this is related only to current lib?

**Comment by micalevisk** [comment]
@Leizhenpeng this is just how the nestjs REPL behaves and, therefore, a limitation of NestJS REPL.

![image](https://user-images.githubusercontent.com/13461315/188285780-84deaca5-ddc3-44aa-9851-88b0fb2c234d.png)

see that there's no chance to replace the logger as the `app` created by `repl()` (from `@nestjs/core`) doesn't expose it

Also, in your code below there's no link between the `app` and `AppModule`. I didn't understand why you expect that any other behavior

![image](https://user-images.githubusercontent.com/13461315/188285828-8332cc87-a5dc-4141-9c60-d62b0d534f41.png)


---


I bet you could propose some non-breaking change on that `repl` at https://github.com/nestjs/nest
