### ISSUE TITLE
How can I add Datadog to Pino?

### ISSUE THREAD

**Issue by gitSambhal** [iamolegga/nestjs-pino#1134]
[x] I've read [the docs of nestjs-pino](https://github.com/iamolegga/nestjs-pino/blob/master/README.md)

[x] I've read [the docs of pino](https://getpino.io/#/)

[x] I couldn't find the same [question about nestjs-pino](https://github.com/iamolegga/nestjs-pino/issues?q=label%3Aquestion)

How can I add Datadog to nest-js pino?

I tried using [pino-datadog-transport](https://www.npmjs.com/package/pino-datadog-transport) package with following options

```
import { LoggerModule } from 'nestjs-pino';

@Module({
  imports: [
    LoggerModule.forRoot({
        {
          pinoHttp: {
            transport: {
              targets: [
                {
                  options: {
                    ignore: 'pid,hostname',
                    levelFirst: true,
                    translateTime: 'UTC:dd/mm/yyyy, h:MM:ss TT Z',
                  },
                  target: 'pino-pretty',
                  level: 'debug',
                },
                {
                  level: 'debug',
                  target: 'pino-datadog-transport',
                  options: {
                    ddClientConf: {
                      authMethods: {
                        apiKeyAuth: config.DATADOG_API_KEY,
                        ddServerConf: { site: 'datadoghq.eu' },
                        ddSource: 'nodejs',
                        service: config.DATADOG_APP_NAME,
                      },
                    },
                  },
                },
              ],
            },
          },
        };
    })
  ],
  ...
})
class MyModule {}
```

but it is not working. 
Please let me know how can I integrate Datadog with Pino in Nestjs with a working example, thank you.

**Comment by iamolegga** [comment]
![image](https://user-images.githubusercontent.com/5501657/191727761-b9a08981-bde2-40e8-b274-c927acecbd7d.png)


https://getpino.io/#/docs/transports?id=pino-v7-compatible

**Comment by gitSambhal** [comment]
@iamolegga I am using the configuration as given in your suggested link but I am not able to make it work. Is there any example of using datadog with nestjs-pino? I am not sure where is the problem, is it in my configuration?

**Comment by iamolegga** [comment]
1. example from [pino docs](https://getpino.io/#/docs/transports?id=pino-datadog-transport):
```ts
const pino = require('pino')
const transport = pino.transport({
  target: 'pino-datadog-transport',
  options: {
    ddClientConf: {
      authMethods: {
        apiKeyAuth: <your datadog API key>
      }
    },
  },
  level: "error", // minimum log level that should be sent to datadog
})
pino(transport) // <--------------------- THIS IS PINO INSTANCE WITH YOUR TRANSPORT
```

2. [pino-http docs](https://github.com/pinojs/pino-http#pinohttpopts-stream) first option `logger`

```ts
pinoHttp: {
  logger: <--- pass transport here
}
```

**Comment by gitSambhal** [comment]
> ```ts
> pino-datadog-transport
> ```

Thanks @iamolegga, Tried it as well but didn't worked. There may be some issue with pino-datadog-transport

**Comment by gitSambhal** [comment]
@iamolegga I did exactly same configuration with nestjs and without nestjs, it is working without nestjs but not working when doing inside nestjs. Any idea?

**Comment by gitSambhal** [comment]
@iamolegga I was able to make it work but there is one issue that the hostname and service name are not showing in Datadog.
<img width="478" alt="Screenshot 2022-09-27 at 9 58 35 AM" src="https://user-images.githubusercontent.com/15196655/192433594-1e9a614c-9b12-4dc8-80d9-f8a2ffdfa1c4.png">
When I used the Winston nestjs package then the service name was showing.

**Comment by gitSambhal** [comment]
> @iamolegga I was able to make it work but there is one issue that the hostname and service name are not showing in Datadog. <img alt="Screenshot 2022-09-27 at 9 58 35 AM" width="478" src="https://user-images.githubusercontent.com/15196655/192433594-1e9a614c-9b12-4dc8-80d9-f8a2ffdfa1c4.png"> When I used the Winston nestjs package then the service name was showing.

Got it working.  It was configuration error in `[pino-datadog-transport](https://github.com/theogravity/pino-datadog-transport)`.

```
  const ddTransportConfigEU: TransportTargetOptions = {
    level,
    options: {
      ddClientConf: {
        authMethods: {
          apiKeyAuth: env.DD_API_KEY,
        },
        ddServerConf: { site: env.DD_SITE },
      },
      ddsource: 'nodejs',
      service: env.DD_SERVICE,
    },
    target: 'pino-datadog-transport',
  };
```
