### ISSUE TITLE
[FEATURE REQUEST] Why is there no support for transports?

### ISSUE THREAD

**Issue by KieronWiltshire** [iamolegga/nestjs-pino#1191]
**Is your feature request related to a problem? Please describe.**
I've created a pino transport for Logtail. I was hoping to use this package to integrate my NestJS logging to Logtail. The issue I have here though is that it seems this package is heavily involved into http context aware logging only. What about logging in other 

**Describe the solution you'd like**
Allow the ability to pass pino options directly to this package and use the pino logger for everything, not just HTTP.

**Describe alternatives you've considered**
Creating my own module.

**Comment by iamolegga** [comment]
there is pinned issue for this feature already

**Comment by KieronWiltshire** [comment]
@iamolegga My apologies. I need this for a project I'm working on, if you can detail a design to take, I can work on a PR if this suits you.

**Comment by iamolegga** [comment]
No worries. Let's keep the discussion in #803 

> if you can detail a design

will answer there
