### ISSUE TITLE
[FEATURE REQUEST] Context outside of requests

### ISSUE THREAD

**Issue by Ginden** [iamolegga/nestjs-pino#1206]
**Is your feature request related to a problem? Please describe.**

Currently, `nestjs-pino` can't add context to Nest.js microservices, CRON calls etc.

**Describe the solution you'd like**

Ability to somehow set context (by decorator or some function) of non-request calls.

**Describe alternatives you've considered**

Theoretically, it's possible to access library internals, access `AsyncLocalStorage` in `storage` and manually set it for current async context.

**Comment by iamolegga** [comment]
duplicate #803
