### ISSUE TITLE
How can I ignore specific API routes from being logged?

### ISSUE THREAD

**Issue by skif48** [iamolegga/nestjs-pino#122]
Hi! Awesome module, thanks!

I have a question though. I've got a Nest.js application and here's my main.ts file:
```typescript
import { NestFactory } from '@nestjs/core';
import { AppModule } from './app.module';
import { Logger } from 'nestjs-pino/dist';

async function bootstrap() {
  process.env.NODE_ENV = process.env.NODE_ENV || 'DEV';
  const app = await NestFactory.create(AppModule, {logger: false});
  app.useLogger(app.get(Logger));
  await app.listen(process.env.PORT || 3000);
}
bootstrap();
```
After I set app.useLogger(...) I can see all the requests coming into the app in stdout. However I have a health check endpoint, which I'd like to prevent from being logged. How can I achieve it with this module?

Thanks in advance.

**Comment by iamolegga** [comment]
Hello, thanks!

The feature of logging req/res is working on top of [pino-http](https://github.com/pinojs/pino-http), it pass options to this module, and it seems like there is no such option to exclude some routes 🤷‍♂️ 

But, I just looked, and I think this can be done on this side. I'll keep this issue open, and will return to it in next few weeks.

By the way, any help is welcome. I think the best way to solve it is by providing optional parameters `forRoutes` and `exclude`, that could be used [here](https://github.com/iamolegga/nestjs-pino/blob/master/src/LoggerCoreModule.ts#L70)

**Comment by iamolegga** [comment]
Hi! Done in v1.0.0

Use `npm install nestjs-pino@latest` and see [migration details](https://github.com/iamolegga/nestjs-pino#migrating)

**Comment by skif48** [comment]
Amazing, thanks! Will check it out ASAP.
