### ISSUE TITLE
[BUG] Doesn't work on Nest 6.7

### ISSUE THREAD

**Issue by JVMartin** [iamolegga/nestjs-pino#125]
**What is the current behavior?**
Nest framework logs are not in JSON format:
![image](https://user-images.githubusercontent.com/4450814/71134010-8e62f780-21b1-11ea-847f-fb0256ee9946.png)

However, injecting PinoLogger into services and using that, those logs are in JSON just fine.

**Please provide the steps to reproduce.**
Simply install following readme instructions into the root module:
```
@Module({
  imports: [
    LoggerModule.forRoot(),
    UsersModule,
  ],
  controllers: [AppController],
})
export class AppModule {}
```

**What is the expected behavior?**
Nest framework logs should be in JSON.

**Please mention other relevant information such as Node.js version and Operating System.**
Node version `v12.13.0`, OS is Ubuntu latest LTR.

According to the Nest docs:
https://docs.nestjs.com/techniques/logger#logger

You can only replace the logger in `NestFactory.create(...);`, which happens in `src/main.ts` in my application.

**Comment by JVMartin** [comment]
Found a partial workaround, following the Nest docs.

Changed `main.ts` from:
```typescript
(async () => {
  const app = await NestFactory.create(AppModule);
  const config = app.get(ConfigService);
  await app.listen(config.port);
})();
```

To:
```typescript
(async () => {
  const app = await NestFactory.create(AppModule);
  app.useLogger(app.get(Logger));  // <-- added this line
  const config = app.get(ConfigService);
  await app.listen(config.port);
})();
```

And now more of the system logs are JSON:
![image](https://user-images.githubusercontent.com/4450814/71134385-ef3eff80-21b2-11ea-8e79-a4613560f688.png)

Looks like it happens asynchronously though and those first logs won't be able to be JSON :thinking:

**Comment by iamolegga** [comment]
Hello, all this is described in docs already:


https://github.com/iamolegga/nestjs-pino/blob/master/README.md#usage-as-nestjs-app-logger

**Comment by prokopsimek** [comment]
@iamolegga Hi, I have the same issue. I understand that it's necessary to add `{ logger: false }` but is there any possibility to log `[InstanceLoader]` and `[NestFactory]` with Pino?

In official documentation is a possibility to [create a new instance of custom logger](https://docs.nestjs.com/techniques/logger#custom-implementation) directly in `NestFactory.create` params.

**Comment by prokopsimek** [comment]
I have another problem - the Nest logger logs all `RouteExplorer`, `RoutesResolver` and `NestApplication` logs but the Pino logs only the first 2 controllers of any module.

**Default logger**
![image](https://user-images.githubusercontent.com/5487217/96839558-a77bab00-1449-11eb-8011-1e1c3c17671d.png)

**PinoLogger with Default logger**
![image](https://user-images.githubusercontent.com/5487217/96839667-c712d380-1449-11eb-92e3-1aa83c4b71e1.png)

**PinoLogger without Default logger**

![image](https://user-images.githubusercontent.com/5487217/96839763-e873bf80-1449-11eb-80ab-08678b7107a2.png)

I am using `LoggerModule.forRoot()` in `app.module.ts`.

Thanks for help.

**Comment by iamolegga** [comment]
> @iamolegga Hi, I have the same issue. I understand that it's necessary to add `{ logger: false }` but is there any possibility to log `[InstanceLoader]` and `[NestFactory]` with Pino?
> 
> In official documentation is a possibility to [create a new instance of custom logger](https://docs.nestjs.com/techniques/logger#custom-implementation) directly in `NestFactory.create` params.
> 
> There is a problem if any error happens due NestFactory creation so there is no error log with the stacktrace.

yep, this is known bug, but as this logger is a little bit complex due to it's functionality and is made in it's own way, that's not matched with official docs. tl;dr there is not such possibility to log `[InstanceLoader]` and `[NestFactory]` from the very start so far, but this can be made in future, see discussion in #353 

> I have another problem - the Nest logger logs all `RouteExplorer`, `RoutesResolver` and `NestApplication` logs but the Pino logs only the first 2 controllers of any module.
> 
> **Default logger**
> ![image](https://user-images.githubusercontent.com/5487217/96839558-a77bab00-1449-11eb-8011-1e1c3c17671d.png)
> 
> **PinoLogger with Default logger**
> ![image](https://user-images.githubusercontent.com/5487217/96839948-22dd5c80-144a-11eb-8269-52008166af35.png)
> 
> **PinoLogger without Default logger**
> 
> ![image](https://user-images.githubusercontent.com/5487217/96839763-e873bf80-1449-11eb-80ab-08678b7107a2.png)
> 
> I am using `LoggerModule.forRoot()` in `app.module.ts`.
> 
> _Note: Ignore the `44` in the console screenshots. It's my custom console.log("44")._
> 
> Thanks for your help.

that could be a bug related to things discussed before, feel free to open new issue with minimal represented example, but it's not critical for most usages, so I'm not sure if I could find time in near future to fix that, sorry, that's open source, that's how it works 😅

**Comment by prokopsimek** [comment]
> sorry, that's open source, that's how it works 😅

lol 😄
