### ISSUE TITLE
[BUG] LoggerErrorInterceptor not populating err property

### ISSUE THREAD

**Issue by rivatove** [iamolegga/nestjs-pino#1250]
- [x] I've read [the docs of nestjs-pino](https://github.com/iamolegga/nestjs-pino/blob/master/README.md)
- [x] I've read [the docs of pino](https://getpino.io/#/) and [pino-http](https://github.com/pinojs/pino-http)
- [x] I couldn't find the same [open issue of nestjs-pino](https://github.com/iamolegga/nestjs-pino/issues)
- [x] This bug is related only to current library or I've tested the same behaviour with the built-in logger and this is not a bug of NestJS.

**What is the current behavior?**

Despite using:
`app.useGlobalInterceptors(new LoggerErrorInterceptor());`
the _err_ property is not populated with uncaught errors.

Interestingly, the _msg_ property does get populated.

**What is the expected behavior?**

The _err_ property gets populated as is the case when logging error objects.

**Please provide minimal example repo, not code snippet. Without example repo this issue will be closed.**

I will include a repo if you confirm that it looks like a bug. I'm not sure if I understood the docs correctly.

**Comment by iamolegga** [comment]
If it's not related to https://github.com/iamolegga/nestjs-pino/issues/1111#issuecomment-1356518712 please add example repo, [err should be populated](https://github.com/iamolegga/nestjs-pino/blob/master/__tests__/logger-error-interceptor.spec.ts#L37-L44)

**Comment by iamolegga** [comment]
closing, neither response nor example repo
