### ISSUE TITLE
[QUESTION]

### ISSUE THREAD

**Issue by ScreamZ** [iamolegga/nestjs-pino#1263]
- [ x ] I've read [the docs of nestjs-pino](https://github.com/iamolegga/nestjs-pino/blob/master/README.md)
- [ x ] I've read [the docs of pino](https://getpino.io/#/) and [pino-http](https://github.com/pinojs/pino-http)
- [ x ] I couldn't find the same [question about nestjs-pino](https://github.com/iamolegga/nestjs-pino/issues?q=label%3Aquestion)
- [ x ] This is not a question about how to use this library with pino-_transport-name-goes-here_

**Question**

Hello, I have the following context for the standalone app

```ts
import { Logger as PinoLogger } from "nestjs-pino";
import { Logger } from "@nestjs/common";
import { NestFactory } from "@nestjs/core";

async bootstrap() {
  const app = await NestFactory.createApplicationContext(AppModule);
  app.useLogger(app.get(PinoLogger));
  app.flushLogs();
  const logger = new Logger();
  logger.info({"test": "test"});
}

bootstrap()
```

I want to use pino-pretty but I'm not sure how, nothing speaks about it here… I would like to achieve the same display in dev mode 
![image](https://user-images.githubusercontent.com/6640835/211208832-6ff7dcb8-8c0a-4d8f-a557-6175f3d3c5f4.png)

**Please mention other relevant information such as Node.js version and Operating System.**

**Comment by iamolegga** [comment]
https://github.com/iamolegga/nestjs-pino#configuration
