### ISSUE TITLE
[BUG] incorrect priority of verbose

### ISSUE THREAD

**Issue by andkom** [iamolegga/nestjs-pino#1268]
NestJS log level priorities:

```typescript
const LOG_LEVEL_VALUES: Record<LogLevel, number> = {
  debug: 0,
  verbose: 1,
  log: 2,
  warn: 3,
  error: 4,
};
```

so in NestJS verbose is **higher** than debug, but in Pino verbose (actually trace) is **lower** than debug.

**Comment by iamolegga** [comment]
can you point the source code for this constant?

I'm not sure if this is not a bug of nestjs, as from my experience `verbose` is lower then `debug`.
Also in the docs in [this section](https://docs.nestjs.com/techniques/logger#custom-implementation) and tight before it levels go like `'log', 'error', 'warn', 'debug', and 'verbose'`, if exclude the first `log` level one can think that other levels go from high to low

**Comment by andkom** [comment]
https://github.com/nestjs/nest/blob/master/packages/common/services/utils/is-log-level-enabled.util.ts#L3

right, verbose is usually lower than debug but not in NestJS

**Comment by iamolegga** [comment]
As I understand correctly, the error will only be for users who migrated from the built-in logger with `verbose` or `debug` levels and set the `trace` or `debug` levels for pino according to the level mapping table from the readme.

And the fix would be to change the mapping from `verbose(nest) -> trace(pino)` and `debug(nest) -> debug(pino)` to `debug(nest) -> trace(pino)` and `verbose(nest) -> debug(pino)`.

Well, to be honest, I think it would be unclear if both loggers had a `debug` level that is not equal to each other, moreover, often the `verbose` level for other (not only JS) loggers is lower than ` debug `. Maybe the best solution here is to add a warning about this next to the level mapping table and keep the same behavior for current users.

**Comment by andkom** [comment]
I migrated logger and spent some time to figure out why verbose does not work.
Maybe we should ask NestJS first if it was made intentionally.

**Comment by iamolegga** [comment]
Agree

**Comment by andkom** [comment]
they won't change behavior

**Comment by iamolegga** [comment]
@andkom as I understood at least before next major release. But this is surely bug/misfunctioning of Nest. The best I can suggest is add a note on this in readme with the link to original issue

**Comment by iamolegga** [comment]
OK, since they decided to fix this in next major, I believe we can close current issue. If you want you can open PR with a note on this somewhere close to levels mapping table
