### ISSUE TITLE
Logger does not match Nest.js Logger

### ISSUE THREAD

**Issue by j** [iamolegga/nestjs-pino#1271]
`nestjs-pino` isn't really a drop in replacement for Nest logger.  We log our messages with Nest.js logger using their format:

```typescript
log(message: any, context?: string): void;
log(message: any, ...optionalParams: [...any, string?]): void;
```

whereas pino Logger is doing the reverse.  So all of our apps logging only gets message and not extraParams.

We log everything like: `logger.log('User Created', { user })` and have to reverse this call to get it to work using this library.

**Comment by j** [comment]
Also other libraries tend to adhere to the proper nest formatting:

https://ogma.jaymcdoniel.dev/en/logger/
https://github.com/gremo/nest-winston
https://github.com/lupu60/nestjs-toolbox/blob/master/packages/bunyan-logger/src/bunyan-logger.service.ts

.. almost all logging libraries I've come across adhere to the internal logger (as they should)

**Comment by iamolegga** [comment]
I'm sorry this library doesn't fit your needs, please choose one from the list above or you can fork this one and make it work for your case.

Current logger implements required interface and there are no requirements on how to pass arguments for logging. So, if pino format doesn't conflict with nest interface I prefer to keep it as is.
