### ISSUE TITLE
[QUESTION] Is there a way to use customLevels?

### ISSUE THREAD

**Issue by nicmesan2** [iamolegga/nestjs-pino#1297]
I am trying to add some customLevels to my Logger. 

I am trying to do the following:

```
@Global()
@Module({
  providers: [LoggerService],
  exports: [LoggerService],
  imports: [LoggerModule.forRoot({
    pinoHttp: {
       logger: pino({customLevels: { aCustomLevel: 99 }})
    }
  })],
})
export class MyLoggerModule {}
```

And then in a custom service:

```
@Injectable()
export class LoggerService extends PinoLogger {
  constructor(@Inject(PARAMS_PROVIDER_TOKEN) params: Params) {
    super(params);
  }

  custom(msg: Message) {
    super.aCustomLevel(msg);
  }
}
```

But I get `aCustomLevel` is not a function.

Am I doing something wrong?

Thanks in advance!

**Comment by iamolegga** [comment]
NestJS has it's own Logger interface.

PinoLogger has only standard methods at the moment.

But you can try to play with [logger field](https://github.com/iamolegga/nestjs-pino/blob/master/src/PinoLogger.ts#L137), maybe that would be enough for your case

If that's doesn't work we can make [call method](https://github.com/iamolegga/nestjs-pino/blob/master/src/PinoLogger.ts#L111) protected to have access to it in sub-classes

**Comment by jmsims2** [comment]
I wasn't able to get the assign method to work exactly. I essentially have 3 extra log methods I need to add and setting the `customLevels` attribute doesn't work. Assign let me assign some fields and methods, but I really just want extra log methods. Have you given any additional thought on if `customLevels` pino option could work with this library?

(apologies if this isn't the right place...I searched for my issue and found this question)

**Comment by iamolegga** [comment]
@jmsims2 please feel free to open a new issue with more details
