### ISSUE TITLE
[QUESTION] How to log response body in serializers ?

### ISSUE THREAD

**Issue by Milan4e** [iamolegga/nestjs-pino#1320]
- [x] I've read [the docs of nestjs-pino](https://github.com/iamolegga/nestjs-pino/blob/master/README.md)
- [x] I've read [the docs of pino](https://getpino.io/#/) and [pino-http](https://github.com/pinojs/pino-http)
- [x] I couldn't find the same [question about nestjs-pino](https://github.com/iamolegga/nestjs-pino/issues?q=label%3Aquestion)
- [x] This is not a question about how to use this library with pino-http

**Question**

Response body (what the client receives) is not logged. I tried the serializers to access the res object, but I was not able to get the response from it. The only data I receive is 

`"res":{"statusCode":304,"headers":{...}},"responseTime":140`

**Comment by iamolegga** [comment]
https://github.com/pinojs/pino-http/issues/173

**Comment by zgldh** [comment]
> * [x]  I've read [the docs of nestjs-pino](https://github.com/iamolegga/nestjs-pino/blob/master/README.md)
> * [x]  I've read [the docs of pino](https://getpino.io/#/) and [pino-http](https://github.com/pinojs/pino-http)
> * [x]  I couldn't find the same [question about nestjs-pino](https://github.com/iamolegga/nestjs-pino/issues?q=label%3Aquestion)
> * [x]  This is not a question about how to use this library with pino-http
> 
> **Question**
> 
> Response body (what the client receives) is not logged. I tried the serializers to access the res object, but I was not able to get the response from it. The only data I receive is
> 
> `"res":{"statusCode":304,"headers":{...}},"responseTime":140`

A work around:

You can setup a `NestInterceptor`
```
@Injectable()
export class MyInterceptor implements NestInterceptor {
  intercept(context: ExecutionContext, next: CallHandler): Observable<any> {
    return next.handle().pipe(
      catchError(err => {
        const response = context.switchToHttp().getResponse();
        // Put your message in header
        response.header('X-Error-Message', err.message);
        return throwError(err);
      }),
    );
  }
}
```

Then config your `pinoHttp.serializers.res`
```
pinoHttp: {
    serializers: {
      res: (resp) => { 
        return {
          xErrorMessage: resp.headers['X-Error-Message'],
        }
      },
    }, 
  },
```
