### ISSUE TITLE
[FEATURE REQUEST] Consider removing postinstall.js to avoid being flagged as Protestware/Troll package by Socket.dev

### ISSUE THREAD

**Issue by mcmxcdev** [iamolegga/nestjs-pino#1357]
**Is your feature request related to a problem? Please describe.**

We recently started using https://socket.dev/ as part of our dependencies maintenance and the tool has flagged `nestjs-pino` as Protestware/Troll package: https://socket.dev/npm/package/nestjs-pino

**Describe the solution you'd like**
You might want to get rid of https://github.com/iamolegga/nestjs-pino/blob/master/postinstall.js to avoid this notice.

**Describe alternatives you've considered**
Ignore the notice

**Comment by iamolegga** [comment]
Sorry, but I don't care at all if some system flag this package somehow. I won't delete it until the war ends. If this breaks your CI just fork it and delete by yourself, but I believe such system should have an option to skip check for certain package
