### ISSUE TITLE
[BUG] doesn't print logs from middleware, interceptor and exception filter

### ISSUE THREAD

**Issue by ianzone** [iamolegga/nestjs-pino#1372]
- [x] I've read [the docs of nestjs-pino](https://github.com/iamolegga/nestjs-pino/blob/master/README.md)
- [x] I've read [the docs of pino](https://getpino.io/#/) and [pino-http](https://github.com/pinojs/pino-http)
- [x] I couldn't find the same [open issue of nestjs-pino](https://github.com/iamolegga/nestjs-pino/issues)
- [x] This bug is related only to the current library or I've tested the same behavior with the built-in logger and this is not a bug of NestJS.

**What is the current behavior?**
doesn't print logs in middleware, interceptor, and exception filter. and it doesn't print the class name from where it's injected. 

**What is the expected behavior?**
print out logs from middleware, interceptor and exception filter, and also indicate from which class. 

**Please provide a minimal example repo, not a code snippet. Without an example repo this issue will be closed.**
https://github.com/ianzone/lambda-nestify/tree/master

**Please mention other relevant information such as Node.js version and Operating System.**
node v18.12.0
OS: Ubuntu 22.04.2 LTS on Windows 10 x86_64
Kernel: 5.15.90.1-microsoft-standard-WSL2

**Comment by iamolegga** [comment]
closing. A **MINIMAL** example repo should be provided

**Comment by ianzone** [comment]
you could
pnpm i -g @antfu/ni @nestjs/cli
ni
nr dev
and then hit any route to see the log

**Comment by ianzone** [comment]
> closing. A **MINIMAL** example repo should be provided

please see above msg

**Comment by iamolegga** [comment]
sorry, but I won't install some third party global modules just to check this particular case.

https://en.wikipedia.org/wiki/Minimal_reproducible_example
https://minimum-reproduction.wtf/
