### ISSUE TITLE
[BUG] 

### ISSUE THREAD

**Issue by serhbs** [iamolegga/nestjs-pino#1396]
- [x] I've read [the docs of nestjs-pino](https://github.com/iamolegga/nestjs-pino/blob/master/README.md)
- [x] I've read [the docs of pino](https://getpino.io/#/) and [pino-http](https://github.com/pinojs/pino-http)
- [x] I couldn't find the same [open issue of nestjs-pino](https://github.com/iamolegga/nestjs-pino/issues)
- [x] This bug is related only to current library or I've tested the same behaviour with the built-in logger and this is not a bug of NestJS.

**What is the current behavior?**

In docker for each reload I see an error:
![image](https://user-images.githubusercontent.com/33103361/227210646-88db3aa8-e6fb-4f5e-a00e-2a755729000c.png)
in dev env

**What is the expected behavior?**
no error

**Please provide minimal example repo, not code snippet. Without example repo this issue will be closed.**
https://github.com/serhbs/nestemplate

**Please mention other relevant information such as Node.js version and Operating System.**
Linux, Docker nodejs 18

**Comment by iamolegga** [comment]
https://stackoverflow.com/questions/4075287/node-express-eaddrinuse-address-already-in-use-kill-server

**Comment by serhbs** [comment]
> https://stackoverflow.com/questions/4075287/node-express-eaddrinuse-address-already-in-use-kill-server

and how it could help with the problem?
