### ISSUE TITLE
[QUESTION] Expose underlaying pino logger instance

### ISSUE THREAD

**Issue by ghost** [iamolegga/nestjs-pino#14]
Hi! Do you think that it would be possible to expose the underlying pino instance so that we can use the convenient syntax to print objects and other variables?

**Comment by iamolegga** [comment]
Hi, if I understand correctly, you don't need to get underlying logger, you can just add params after `context` argument, look here:

https://github.com/iamolegga/nestjs-pino/blob/master/src/index.ts#L66

Is this the correct answer?

**Comment by iamolegga** [comment]
Closing this for now, feel free to reopen.

Also, I think you could be interesting in https://github.com/iamolegga/nestjs-pino/issues/22
