### ISSUE TITLE
[QUESTION] possible to log responseBody in request complete

### ISSUE THREAD

**Issue by kundkingan** [iamolegga/nestjs-pino#1405]
- [x] I've read [the docs of nestjs-pino](https://github.com/iamolegga/nestjs-pino/blob/master/README.md)
- [x] I've read [the docs of pino](https://getpino.io/#/) and [pino-http](https://github.com/pinojs/pino-http)
- [x] I couldn't find the same [question about nestjs-pino](https://github.com/iamolegga/nestjs-pino/issues?q=label%3Aquestion)
- [x] This is not a question about how to use this library with pino-_transport-name-goes-here_

**Question**

Is it possible to log response body with the request complete log? 

Currently in the `res` serializers, it's not possible to access the returning body to add it to the final log.

**Please mention other relevant information such as Node.js version and Operating System.**

**Comment by iamolegga** [comment]
this IS a question about `pino-http` as the current library is only a `NestJS` wrapper for it

https://github.com/pinojs/pino-http/issues?q=body
