### ISSUE TITLE
[BUG] logger does not work inside onApplicationShutdown() hook

### ISSUE THREAD

**Issue by rosko01** [iamolegga/nestjs-pino#1408]
- [x] I've read [the docs of nestjs-pino](https://github.com/iamolegga/nestjs-pino/blob/master/README.md)
- [x] I've read [the docs of pino](https://getpino.io/#/) and [pino-http](https://github.com/pinojs/pino-http)
- [x] I couldn't find the same [open issue of nestjs-pino](https://github.com/iamolegga/nestjs-pino/issues)
- [x] This bug is related only to current library or I've tested the same behaviour with the built-in logger and this is not a bug of NestJS.

**What is the current behavior?**

Using a logger inside a Nestjs onApplicationShutdown() hook does not emit any log messages to the console at all.

**What is the expected behavior?**

Log messages inside the onApplicationShutdown() should work just like they do inside onApplicationBootstrap()

**Please mention other relevant information such as Node.js version and Operating System.**

Node.js 18.x
NestJS 9.3.x
nestjs-pino 3.1.2

**Comment by iamolegga** [comment]
https://github.com/iamolegga/nestjs-pino/blob/master/.github/ISSUE_TEMPLATE/bug_report.md?plain=1#L22
