### ISSUE TITLE
[QUESTION] Is it possible to make it so errors are logged to stderr?

### ISSUE THREAD

**Issue by ropbastos** [iamolegga/nestjs-pino#1409]
- [X] I've read [the docs of nestjs-pino](https://github.com/iamolegga/nestjs-pino/blob/master/README.md)
- [X] I've read [the docs of pino](https://getpino.io/#/) and [pino-http](https://github.com/pinojs/pino-http)
- [X] I couldn't find the same [question about nestjs-pino](https://github.com/iamolegga/nestjs-pino/issues?q=label%3Aquestion)
- [X] This is not a question about how to use this library with pino-_transport-name-goes-here_

I want to use this library, but also be notified of prints to stderr. Is it possible to make this library print to stderr?

**Please mention other relevant information such as Node.js version and Operating System.**

**Comment by iamolegga** [comment]
https://github.com/pinojs/pino/

**Comment by steebchen** [comment]
Can this be re-opened? I can only find

https://github.com/pinojs/pino/blob/master/docs/help.md#log-to-different-streams

in the main repo, but the mentioned pino-multistream package is deprecated, and it's unclear how to use the options with the way you set up Pino with NestJS.

**Comment by iamolegga** [comment]
This question should be addressed in appropriate projects. Current one is just a wrapper on top of nestjs and pino-http
