### ISSUE TITLE
[FEATURE REQUEST] peer dependencies support v10 of NestJS

### ISSUE THREAD

**Issue by fatlirmorina** [iamolegga/nestjs-pino#1491]
**Is your feature request related to a problem? Please describe.**
Could be a huge problem in the near future.

**Describe the solution you'd like**
As far as we know v10 has just released however this is now causing errors for the package to be added.

Could you update peer dependencies of the package? would of been appreciated.

Note that they no longer support typescript below 4.8
https://docs.nestjs.com/migration-guide#cli-plugins-and-typescript--48

**Describe alternatives you've considered**
#

**Additional context**
#

**Comment by iamolegga** [comment]
Published in `3.3.0`
