### ISSUE TITLE
[QUESTION] | How to integrate it with pino-elasticsearch?

### ISSUE THREAD

**Issue by ashish-moglix** [iamolegga/nestjs-pino#1514]
- [x] I've read [the docs of nestjs-pino](https://github.com/iamolegga/nestjs-pino/blob/master/README.md)
- [x] I've read [the docs of pino](https://getpino.io/#/) and [pino-http](https://github.com/pinojs/pino-http)
- [x] I couldn't find the same [question about nestjs-pino](https://github.com/iamolegga/nestjs-pino/issues?q=label%3Aquestion)
- [x] This is not a question about how to use this library with pino-_transport-name-goes-here_

**Question**
I tried to integrate nestjs-pino with pino-elsasticsearch but unfortunately either I am missing something or integration is not supported.

- I did following setup to run elastic and kibana -

`
version: '3'
services:
  elasticsearch:
    image: elasticsearch:7.8.1
    ports:
      - 9200:9200
    environment:
      discovery.type: 'single-node'
      xpack.security.enabled: 'true'
      ELASTIC_PASSWORD: '1234'
  kibana:
    image: kibana:7.8.1
    # image: kibana:6.5.4
    volumes:
      - ./config/kibana.yml:/usr/share/kibana/config/kibana.yml
    ports:
      - 5601:5601
`

-  and created a stream of elastic with pino-elasticsearch with following config -
`
const streamToElastic = pinoElastic({
  index: 'secure-proxy',
  consistency: 'one',
  node: 'http://localhost:9200',
  auth: {
    username: 'elastic1',
    password: 1234,
  },
  'es-version': 7,
  'flush-bytes': 10,
  'flush-interval': 100,
  'trace-level': 'debug',
  ecs: true,
});

streamToElastic.on('unknown', (line: any, error: any) =>
  console.log(
    'Expect to see a lot of these with Pino Pretty turned on.',
    line,
    error,
  ),
);

// Capture errors like unable to connect Elasticsearch instance.
streamToElastic.on('error', (error: any) => {
  console.error('Elasticsearch client error:', error);
});
// Capture errors returned from Elasticsearch, "it will be called for everytime a document can't be indexed".
streamToElastic.on('insertError', (error: any) => {
  console.error('Elasticsearch server insert error:', error);
});
streamToElastic.on('insert', (stats: Record<string, any>) => {
  console.log(stats);
});
`

- Provided streamToElastic as pinoHttp: [{},streamToElastic] as following -
`
LoggerModule.forRootAsync({
      useFactory: () => ({
        pinoHttp: [
          {
            autoLogging: false,
            level: 'info',
            redact: {
              paths: [
                `req.headers["${API_SECRET}"]`,
                `req.headers["${API_TOKEN}"]`,
                `req.body.accessToken`,
                `req.body.refreshToken`,
                'resp.accessToken',
                'resp.refreshToken',
              ],
            },
            genReqId: () => uuid4(),
            // eslint-disable-next-line @typescript-eslint/no-unused-vars
            customProps: (_req: any, _res: any) => ({
              context: 'HTTP',
              clientIp: _req.ip,
              'x-forwarded-for': _req.headers['X-FORWARDED-FOR'],
            }),
            serializers: {
              req: (req) => {
                req.body = req.raw?.body;
                return req;
              },
            },
            transport: {
              targets: [
                {
                  target: 'pino-pretty',
                  level: 'info',
                  options: {
                    colorize: true,
                    singleLine: true,
                    ignore: 'pid,hostname',
                    errorLikeObjectKeys: ['err', 'error'],
                  },
                },
                {
                  target: 'pino/file',
                  level: 'debug',
                  options: {
                    destination: './logs/secure-proxy-debug.log',
                    mkdir: true,
                  },
                },
                {
                  target: 'pino/file',
                  level: 'error',
                  options: {
                    destination: './logs/secure-proxy-error.log',
                    mkdir: true,
                  },
                },
              ],
            },
          },
          streamToElastic,
        ],
      }),
    }),
`

- with above config I am able to log everything to multiple targets but logs are not flowing to elastic search.
- Neither logger index is created
- Nor any of the error listener is invoked

**Is there an alternative of config changes needed so that I can push logs to elastic**

**Please mention other relevant information such as Node.js version and Operating System.**
node - v18.16.0
npm - 9.5.1
"nestjs-pino": "^3.2.0",
"pino-elasticsearch": "^6.4.0",
"pino-http": "^8.3.3",
"pino-pretty": "^10.0.0",

**Comment by iamolegga** [comment]
![image](https://github.com/iamolegga/nestjs-pino/assets/5501657/f74692a0-4716-4344-a3f8-48b98082fccc)

just read the docs of the current library carefully, closing
