### ISSUE TITLE
[QUESTION] how to disable logging for some context

### ISSUE THREAD

**Issue by rubiin** [iamolegga/nestjs-pino#1536]
- [x] I've read [the docs of nestjs-pino](https://github.com/iamolegga/nestjs-pino/blob/master/README.md)
- [x] I've read [the docs of pino](https://getpino.io/#/) and [pino-http](https://github.com/pinojs/pino-http)
- [x] I couldn't find the same [question about nestjs-pino](https://github.com/iamolegga/nestjs-pino/issues?q=label%3Aquestion)
- [x] This is not a question about how to use this library with pino-_transport-name-goes-here_

**Question**

I have context such as BootStrap as well as RouterExplorer . Is there a way i could tell pino to ignore these context. Using log level is not an option in this case.

Trying to do something like this https://dev.to/micalevisk/nestjs-tip-how-to-disable-initialization-logging-1b38

**Please mention other relevant information such as Node.js version and Operating System.**

**Comment by iamolegga** [comment]
It looks like extending the original logger class is the right way to do what you want, why not?
