### ISSUE TITLE
[QUESTION] How to pass userId meta in decorator or guard?

### ISSUE THREAD

**Issue by MikeKoval** [iamolegga/nestjs-pino#1590]
Hi!

I want to append userId meta for logs.

Auth is realized via decorator
https://docs.nestjs.com/custom-decorators#passing-data

https://github.com/iamolegga/nestjs-pino#assign-extra-fields-for-future-calls
Assign works just fine in scope of controller, but how to assign meta info in decorator or guard?
I simple cannot access logger instance from controller in decorator.
PinoLogger.root.setBindings does not work there also.
 
I think docs lack of that info, that is most popular usage of logs meta i think.
Existing example does not represent real usage, nobody will assign userId meta in each controller, agree?

I managed to pass userId meta in customProps of pinoHttp from request but i managed to get userId only in complete request message, all messages between request and response do not have that meta.

Thank you!

**Comment by iamolegga** [comment]
I didn't get the question. Are you going to use the logger as a transport for `userId` between layers?

**Comment by MikeKoval** [comment]
no.
I have controller that looks like this (simplified versions)

```import { Get } from '@nestjs/common';
import { PinoLogger } from 'nestjs-pino';
import Auth from "./common/decorators/auth.decorator";

export class AppController {
  constructor(private logger: PinoLogger) {}

  @Get()
  async getHealthcheck(@Auth() user) {
    this.logger.info('test_from_controller');
    return {
      ok: true
    }
  }
}

```

and i have decorator that looks like this

```
import {
  createParamDecorator,
  ExecutionContext,
} from '@nestjs/common';

export default createParamDecorator(
  async (data: string, ctx: ExecutionContext) => {
  const user = { id: 1 };
    return user;
  },
);
```

i want to get test_from_controller message in logs with userId: 1 meta, but i dont want to "assign" userId in each controller method as there might be many of them, i want to assign that meta inside decorator or some another implementation where its assigned once.

**Comment by MikeKoval** [comment]
Thank you!

**Comment by iamolegga** [comment]
> i want to get test_from_controller message in logs with userId: 1 meta, but i dont want to "assign" userId in each controller method as there might be many of them, i want to assign that meta inside decorator or some another implementation where its assigned once.

The simplest solution is pass `serializers` field in config:

```ts
  serializers: {
    req: (req) => {
      // take it from session or headers or whatever where you keep it
      // just be sure that logger middleware works after your session/auth middleware
      // if it has to be done before getting access to that field
      req.userId = req.raw.session?.user.id || null,
      return req;
    },
  },
```

Does it help?

**Comment by iamolegga** [comment]
No response, closing
