### ISSUE TITLE
[BUG] Basic configuration with Usage as NestJS app logger doesn't work

### ISSUE THREAD

**Issue by dlecan** [iamolegga/nestjs-pino#162]
**What is the current behavior?**

Basic configuration as described by [Usage as NestJS app logger](https://github.com/iamolegga/nestjs-pino#usage-as-nestjs-app-logger) doesn't work.

**Please provide the steps to reproduce.**

On a NestJS 6.10.10 project, just :
```
import { Logger } from "nestjs-pino";

const app = await NestFactory.create(MyModule, { logger: false });
app.useLogger(app.get(Logger));
```

gives:

```
Error: Nest could not find Logger element (this provider does not exist in the current context)
    at ContainerScanner.getWrapperCollectionPairByHost (/myproject/node_modules/@nestjs/core/injector/container-scanner.js:34:19)
    at ContainerScanner.findInstanceByToken (/myproject/node_modules/@nestjs/core/injector/container-scanner.js:20:40)
    at ContainerScanner.find (/myproject/node_modules/@nestjs/core/injector/container-scanner.js:13:21)
    at NestApplication.find (/myproject/node_modules/@nestjs/core/nest-application-context.js:184:38)
    at NestApplication.get (/myproject/node_modules/@nestjs/core/nest-application-context.js:43:25)
    at /myproject/node_modules/@nestjs/core/nest-factory.js:112:40
    at Function.run (/myproject/node_modules/@nestjs/core/errors/exceptions-zone.js:8:13)
    at Proxy.<anonymous> (/myproject/node_modules/@nestjs/core/nest-factory.js:111:46)
    at bootstrap (/myproject/dist/src/main.js:9:23)
    at processTicksAndRejections (internal/process/task_queues.js:85:5)
```

**What is the expected behavior?**

**Please mention other relevant information such as Node.js version and Operating System.**

NodeJS: 12.9.1
NestJS: 6.10.10

**Comment by iamolegga** [comment]
Hi, @dlecan have you imported `LoggerModule` to your `MainModule` ?

**Comment by iamolegga** [comment]
Closing issue for no response. Read all the docs please

**Comment by dlecan** [comment]
Hi, thank you for your answer.

When I read the chapter [Usage as NestJS app logger](https://github.com/iamolegga/nestjs-pino#usage-as-nestjs-app-logger) (Level 2, same as "Install", so no reason to read "install" chapter), by reading the documentation, I did not know that an additional configuration should have been done.

Now, anyone will know it by searching the repository and by reading your answer.
Thank you.

**Comment by nodejsdeveloperskh** [comment]
> Hi, @dlecan have you imported `LoggerModule` to your `MainModule`?

Add this code in your `app.module.ts`

```ts
@Module({
    imports: [
        WinstonModule.forRootAsync({
            useFactory: async (
                configService: ConfigService,
            ): Promise<winston.LoggerOptions> => ({
                ...configService.get<winston.LoggerOptions>(
                    'loggerOptions',
                ),
            }),
            inject: [ConfigService],
        }),
        ConfigModule.forRoot({
            isGlobal: true,
            envFilePath: ['.env', '.env.mongo'],
            load: [
                authConfigsGenerator,
                mongodbConfigsGenerator,
                webAppConfigsGenerator,
                winstonConfigsGenerator,
            ],
        }),
    ],
})
export class AppModule {}
```

An example/boilerplate : https://github.com/nodejsdeveloperskh/project-schema/tree/nestjs-mongoose

**Comment by Nishimirwe** [comment]
Please check whether you have imported LoggerModule to your MainModule (app.module.ts)?
