### ISSUE TITLE
[QUESTION] Fetch request ID 

### ISSUE THREAD

**Issue by amit12cool** [iamolegga/nestjs-pino#164]
Im using below code to generate request ID:-

```
shared.module.ts

import {
  Module,
  HttpModule
} from '@nestjs/common';
import { MongooseModule } from '@nestjs/mongoose';
import { APP_FILTER } from '@nestjs/core';
import { LoggerModule } from 'nestjs-pino';
import * as config from 'config';

import { CorrelationIdGeneratorService } from './services/helpers/generators/correlation-id-generator.service';


@Module({
  imports: [
    MongooseModule.forFeature([{ name: 'Device', schema: DeviceSchema }]),
    MongooseModule.forFeature([{ name: 'File', schema: FileSchema }]),
    HttpModule,
    LoggerModule.forRootAsync({
      providers: [
        CorrelationIdGeneratorService,
      ],
      inject: [CorrelationIdGeneratorService],
      useFactory: (correlationIdGeneratorService: CorrelationIdGeneratorService) => {
        return {
          pinoHttp: {
            genReqId: (request) => {
              correlationIdGeneratorService.generateCorrelationId(request);
              console.log('Im here 1',correlationIdGeneratorService.getCorrelationId());
              return correlationIdGeneratorService.getCorrelationId();
            },
            level: config.get('log.LEVEL'),
            useLevelLabels: true,
            base: null,
            timestamp: () => {
              return `, "time":"${new Date().toISOString()}"`;
            },
          },
        };
      }
    })
  ],
  providers: [
    CorrelationIdGeneratorService,
  ],
  exports: [
    CorrelationIdGeneratorService,
  ]
})
export class SharedModule { }

```

Now the issue is, i need to fetch the correlationId in another module for which i have exported the CorrelationIdGeneratorService from shared.module.ts and imported in my consuming modules.

Now in the consuming module im getting correlationId as undefined. 

It seems that the object of CorrelationIdGeneratorService passed in loggermodule is different from the object passed in my consuming module. Please help, how can i share the singleton instance of correlation id throughout my code.

Below is the code for CorrelationIdGeneratorService 
correlation-id-generator.service.ts
```
import { Injectable } from '@nestjs/common';
import * as config from 'config';

import { UniqueIdGeneratorService } from './unique-id-generator.service';

@Injectable()
export class CorrelationIdGeneratorService {
    private correlationId: string;
    constructor(private readonly uniqueIdGeneratorService: UniqueIdGeneratorService) {}

    public generateCorrelationId(request: any) {
        this.correlationId = request?.headers?.[config.get('httpHeaders.CORRELATION_ID')] ||
        this.uniqueIdGeneratorService.generate(
            config.get('correlationId.VALID_CHARS'),
            config.get('correlationId.LENGTH')
        );
        console.log('Ammy 2', this.correlationId)
    }

    public getCorrelationId(): string {
        return this.correlationId;
    }
}
```

**Comment by amit12cool** [comment]
Anyway to use requestId in other class?

**Comment by iamolegga** [comment]
Please provide some minimal represented repo, without mongo and all other unnecessary things

**Comment by iamolegga** [comment]
Closing, feel free to continue discussion

**Comment by amit12cool** [comment]
This is resolved for me now.
Solution:- Im generating new requestId in middleware for each request and updating the request object with the requestId property.

**Comment by amit12cool** [comment]
@iamolegga  Actually there is one scenario in which I need to generate requestId which is not handled by nestjs Pino. The scenario is as below:-

We get some events from a publisher in our nodejs code. Now I need to log that request(event) and generate new unique requestId. The issue is how genReqId() can be called in this scenario?

**Comment by iamolegga** [comment]
If I understand correctly, can you also store `genReqId` function in variable of global or module scope when you define it?

**Comment by amit12cool** [comment]
Yes, so that request ID can be updated from lets say at the entry point of request or the origin of request is an event from Azure Event hub on reception of which the request Id can be generated.

**Comment by iamolegga** [comment]
Maybe you can provide tiny example?

**Comment by amit12cool** [comment]
I could but Im short of time. Sorry. 
Scenario I can again explain:-

I have a event listener which receives the event from cloud. Now i need print the logs with requestID generated. Will my genReqId() method be called in this case. If not, how can we do that?

**Comment by iamolegga** [comment]
Only thing that I can suggest is export that `genReqId` directly or assign it to some variable and call it at any place you want 🤷‍♂️

**Comment by amit12cool** [comment]
You mean to export from the logger module.

Get Outlook for Android<https://aka.ms/ghei36>
________________________________

**Comment by amit12cool** [comment]
Basically how can i call genReqId from anywhere in the code?

**Comment by iamolegga** [comment]
If you need some deps to create this function, you can assign it to variable, and `export` function that returns this variable
