### ISSUE TITLE
[QUESTION] Have 'context' key outside of 'nestedKey' object

### ISSUE THREAD

**Issue by random42** [iamolegga/nestjs-pino#1644]
- [X] I've read [the docs of nestjs-pino](https://github.com/iamolegga/nestjs-pino/blob/master/README.md)
- [X] I've read [the docs of pino](https://getpino.io/#/) and [pino-http](https://github.com/pinojs/pino-http)
- [X] I couldn't find the same [question about nestjs-pino](https://github.com/iamolegga/nestjs-pino/issues?q=label%3Aquestion)
- [X] This is not a question about how to use this library with pino-_transport-name-goes-here_

**How to make 'context' key be outside of 'nestedKey' object**

Hi,

In my pino-http configuration I set the 'nestedKey' option in order to separate actual logged data from default pino data (reqId, msg, pid, etc.). The problem is that the 'context' key appears in my 'nestedKey', and I'd like it to be in the root object, so that I will never accidentally overwrite it.

I do not have found a solution to this, can anyone help?

**Comment by iamolegga** [comment]
I didn't get the question, Could you provide actual/desired log formats and current configuration with only fields related to this question?

**Comment by random42** [comment]
Example (I'm excluding all nest bootstrap and stuff):

```typescript
import { LoggerModule } from 'nestjs-pino';
import { Logger } from '@nestjs/common';

const module = LoggerModule.forRoot({
  pinoHttp: {
    nestedKey: 'data',
    quietReqLogger: true,
  },
});

const log = new Logger('my-context');
log.log({ my: 'data'});

```

Output log:

```json
{
  "reqId": 1,
  "data": {
    "context": "my-context",
    "my": "data"
  }
}
```

Desired output:
```json
{
  "reqId": 1,
  "context": "my-context",
  "data": {
    "my": "data"
  }
}
```

**Comment by iamolegga** [comment]
In the end, pino logger is called like so: `pino[level]({ context: 'value', ...restOptions })`. I don't know if it's possible to move `context` field to the root of the log object. Is it possible to log some fields in the root with plain https://github.com/pinojs/pino-http ?

**Comment by iamolegga** [comment]
No response, closing. If you're still interested in this please check pino-http first, and then if that's possible with pino-http we could reopen this issue.
