### ISSUE TITLE
[FEATURE REQUEST] set the loggers scope values for its lifetime

### ISSUE THREAD

**Issue by jbw** [iamolegga/nestjs-pino#1645]
**Is your feature request related to a problem? Please describe.**

The problem I have is duplicating a contextual set of properties for each log when I want to capture the current context of the logging operations. For example, in code handlers that work on a given "job" that has job metadata, I would like to log them each time so I can query it in the context of that job by its ID. Currently, I have to copy those values for each log which is noisy in the code and often multilines.

**Describe the solution you'd like**

I would like custom properties to be in logs for the lifetime of a logger. 

For example to log values within the scope of a single transaction in a handler. I thought this would fit into the `setContext` method, but it only supports a string value. So maybe a setScope method would work or adding an extra optional param to context.

>"A scope can group a set of logical operations. This grouping can be used to attach the same data to each log that's created as part of a set. For example, every log created as part of processing a transaction can include the transaction ID." - https://learn.microsoft.com/en-us/aspnet/core/fundamentals/logging/?view=aspnetcore-7.0#log-scopes

Example

```ts
this.logger.setScope({ id, jobId, groupId });
this.logger.log('hello');
```

Then subsequent logs would include `scope` object

```
{  "msg": "hello", "scope":{ "id": "", "jobId":"", "groupId":"" } }
```

Instead of something like:

```ts
this.logger.log('hello1', { id, jobId, groupId });
this.logger.log('hello2', { id, jobId, groupId });
this.logger.log('hello3', { id, jobId, groupId });
```

**Describe alternatives you've considered**

- Repeat the above for each log if it supports key-value pair logging.
- String variable such as `loggingPrefix` and using it to prefix each log. 

These options are noisy in the code and not structured logs in the string prefix workaround which makes it harder to query

**Additional context**

LogScopes is a similar idea used by .NET logging.
https://learn.microsoft.com/en-us/aspnet/core/fundamentals/logging/?view=aspnetcore-7.0#log-scopes

**Comment by iamolegga** [comment]
https://github.com/iamolegga/nestjs-pino?tab=readme-ov-file#assign-extra-fields-for-future-calls
