### ISSUE TITLE
How to inject PinoLogger into TestingModule?

### ISSUE THREAD

**Issue by aetherplex** [iamolegga/nestjs-pino#1698]
- [ x] I've read [the docs of nestjs-pino](https://github.com/iamolegga/nestjs-pino/blob/master/README.md)
- [ x] I've read [the docs of pino](https://getpino.io/#/) and [pino-http](https://github.com/pinojs/pino-http)
- [x ] I couldn't find the same [question about nestjs-pino](https://github.com/iamolegga/nestjs-pino/issues?q=label%3Aquestion)
- [x ] This is not a question about how to use this library with pino-_transport-name-goes-here_

**Question**
How can I inject PinoLogger into my TestingModule?  

I have a service that looks like this:
```ts
constructor(
        @InjectPinoLogger(Service.name)
        private readonly logger: PinoLogger,
)
{}
```
I need to inject PinoLogger into the TestingModule:
```ts
const module: TestingModule = await Test.createTestingModule({
    providers: [
        Service,
        {
            provide: InjectPinoLogger(Service.name),
            useValue: {
                error: jest.fn(),
                warn: jest.fn(),
                info: jest.fn(),
                debug: jest.fn(),
            },
        },
```

But the above does't seem to work.

**Please mention other relevant information such as Node.js version and Operating System.**

**Comment by iamolegga** [comment]
Does this help
https://github.com/iamolegga/nestjs-pino?tab=readme-ov-file#testing-a-class-that-uses-injectpinologger ?

**Comment by aetherplex** [comment]
It does, thank you!
