### ISSUE TITLE
[QUESTION] Setting context on extended Logger

### ISSUE THREAD

**Issue by coler-j** [iamolegga/nestjs-pino#1766]
- [x] I've read [the docs of nestjs-pino](https://github.com/iamolegga/nestjs-pino/blob/master/README.md)
- [x] I've read [the docs of pino](https://getpino.io/#/) and [pino-http](https://github.com/pinojs/pino-http)
- [x] I couldn't find the same [question about nestjs-pino](https://github.com/iamolegga/nestjs-pino/issues?q=label%3Aquestion)
- [x] This is not a question about how to use this library with pino-_transport-name-goes-here_

**Question**

How do I `setContext` when using an extended class? That interface does not exist on the Logger object exported by nestjs-pino.

I do not see an example in the tests which use extending: https://github.com/iamolegga/nestjs-pino/blob/master/__tests__/extending.spec.ts

**Comment by iamolegga** [comment]
I would say it's better to not extend `Logger` class and use it only as a substitution for built-in `Logger` class implementation. An extension support was added a long time ago before nest@8 which introduced logger substitution, so after that `Logger` class purpose is only to be used internally by Nest. If you need some extra logic for your custom logger I would suggest using `PinoLogger` which has [setContext](https://github.com/iamolegga/nestjs-pino/blob/a1f59b83335b9eaadddc7f66938109ca00e61867/src/PinoLogger.ts#L125) method

**Comment by coler-j** [comment]
Ok thanks,

My use case was automating some trace logic which I wanted to occur on every `logger.error`.

I ended up implementing a custom serialization method to do this logic instead:

```
@Module({
  imports: [
    PinoLoggerModule.forRootAsync({
      useFactory: () => ({
            pinoHttp: {
                 serializers: {
                    err: (error: Error) => {
                        .... // my logic to annotate traces
                        return pino.stdSerializers.err(error);
                    }
                }
            }
        }),
    }),
  ],
})
```
