### ISSUE TITLE
[BUG] Double `request completed` in my logs

### ISSUE THREAD

**Issue by eropple** [iamolegga/nestjs-pino#1790]
- [x] I've read [the docs of nestjs-pino](https://github.com/iamolegga/nestjs-pino/blob/master/README.md)
- [x] I've read [the docs of pino](https://getpino.io/#/) and [pino-http](https://github.com/pinojs/pino-http)
- [x] I couldn't find the same [open issue of nestjs-pino](https://github.com/iamolegga/nestjs-pino/issues)
- [x] This bug is related only to current library or I've tested the same behaviour with the built-in logger and this is not a bug of NestJS.

**What is the current behavior?**
When I run my application, I get two `request completed` lines. For example:

```json
{"level":30,"time":1703711217809,"pid":308103,"hostname":"workshop-pc-linux","name":"coreapi","context":"NestApplication","msg":"Nest application successfully started"}
{"level":30,"time":1703711225712,"pid":308103,"hostname":"workshop-pc-linux","name":"coreapi","req":{"id":2,"method":"GET","params":{"0":"meta/ping/5"},"headers":{"host":"localhost:5000","user-agent":"curl/8.2.1","accept":"*/*"},"remoteAddress":"::1"},"context":"MetaController","count":5,"msg":"Ping!"}
{"level":30,"time":1703711225713,"pid":308103,"hostname":"workshop-pc-linux","name":"coreapi","req":{"id":2,"method":"GET","params":{"0":"meta/ping/5"},"headers":{"host":"localhost:5000","user-agent":"curl/8.2.1","accept":"*/*"},"remoteAddress":"::1"},"res":{"statusCode":200,"headers":{"content-type":"application/json; charset=utf-8","content-length":"50","etag":"W/\"32-p5UFQz8e/1yEhpTOC7w2e+nUr78\""}},"responseTime":3,"msg":"request completed"}
{"level":30,"time":1703711225713,"pid":308103,"hostname":"workshop-pc-linux","name":"coreapi","req":{"id":2,"method":"GET","params":{"0":"meta/ping/5"},"headers":{"host":"localhost:5000","user-agent":"curl/8.2.1","accept":"*/*"},"remoteAddress":"::1"},"res":{"statusCode":200,"headers":{"content-type":"application/json; charset=utf-8","content-length":"50","etag":"W/\"32-p5UFQz8e/1yEhpTOC7w2e+nUr78\""}},"responseTime":3,"msg":"request completed"}
```

This sounds like #1500, but I have a repro case for you.

**What is the expected behavior?**
One `request completed` line.

**Please provide minimal example repo, not code snippet. Without example repo this issue will be closed.**
This is about as minimal as I can get with the time I have available to me: https://github.com/eropple/nestjs-pino-double-log-reproduction

```bash
cd nestjs-pino-double-log-reproduction
npm install
cd apps/coreapi
npm run start:api:dev
```

Then try to curl http://localhost:5000/meta/ping/3 and you'll see them.

For Reasons(tm), the server runs through a CLI entry point. Files of interest (in the order they're executed):
- `src/entry-point.ts`
- `src/_cli/run.ts`
- `src/main-api.ts`
- `src/_api/api.module.ts`
- `src/_api/meta/meta.controller.ts`

This also **does not** happen when I wrote my own request logging middleware and register it in `AppModule`; nestjs-pino is registering something twice, somewhere.

**Please mention other relevant information such as Node.js version and Operating System.**
Tested on Linux and MacOS, Node 18.19.0 and 20.10.0. Same behavior.

Thanks!

**Comment by iamolegga** [comment]
Thanks for reporting. Please create a really [minimal example repo](https://minimum-reproduction.wtf/). Just init a new nest project with nest CLI and add this library. Your example has many dependencies that could lead to this bug. Until then I'm closing this issue. Thanks

**Comment by eropple** [comment]
First: your library is your library, and your time is your time. You should do what you feel is right.

Second: I don't really have time or inclination to do that, when every other library and system works predictably. You've got two reports of this bug, and a working test case. Yes, there are dependencies here--but there's a _problem with nestjs-pino_ here, whether by itself or in conjunction with mainline libraries and used-by-the-label Nest libraries and tools.

What you do with it is absolutely up to you, but I'm more inclined to go remove your library from my system and implement it, [as I've done before](https://github.com/eropple/nestjs-bunyan).

**Comment by eropple** [comment]
First: your library is your library, and your time is your time. You should do what you feel is right.

Second: I don't really have time or inclination to dig further, when every other library and system in my Nest application works predictably. You've got two reports of this bug with #1500 and a working test case. Yes, there are dependencies here--that's because I minimized a production application that's using NestJS in ways it contractually permits. If I go `nest new` and it works, that doesn't delegitimize the bug--the problem is still with nestjs-pino's interactions with things being used as Nest permits them to be used, and that's a bug (either in code or documentation). Which is why I provided a minimized production application for your consideration and not a toy repro: because it's more illustrative of the actual problem.

What you do with this bug report is absolutely up to you, but disqualifying a repeat bug, with repro, because it's not sufficiently a-toy-repro is discouraging towards using the library at all.

**Comment by iamolegga** [comment]
I'm very sorry that you are dissatisfied with the quality of this open source product. I can only recommend looking for alternatives.
