### ISSUE TITLE
Support pino-http 9.x

### ISSUE THREAD

**Issue by swcm-mnestler** [iamolegga/nestjs-pino#1794]
Thank you for this useful library! Currently using `nestjs-pino@3.5.0` with `pino-http` which now has a new release `9.0.0` available. As far as I can tell, the only breaking changes in that release were changes to the supported node versions. Please add that version as a supported `peerDependency` so we can stay on the latest `pino-http`

```
❯ npm i --no-progress
npm WARN ERESOLVE overriding peer dependency
npm WARN While resolving: <snip>
npm WARN Found: pino-http@8.6.1
npm WARN node_modules/pino-http
npm WARN   pino-http@"9.0.0" from the root project
npm WARN   1 more (nestjs-pino)
npm WARN 
npm WARN Could not resolve dependency:
npm WARN peer pino-http@"^6.4.0 || ^7.0.0 || ^8.0.0" from nestjs-pino@3.5.0
npm WARN node_modules/nestjs-pino
npm WARN   nestjs-pino@"3.5.0" from the root project
```

**Comment by iamolegga** [comment]
released in 4.0.0
