### ISSUE TITLE
Pino Multistream / Multi-transports ?

### ISSUE THREAD

**Issue by palbrecht1** [iamolegga/nestjs-pino#1830]
- [x] I've read [the docs of nestjs-pino](https://github.com/iamolegga/nestjs-pino/blob/master/README.md)
- [x] I've read [the docs of pino](https://getpino.io/#/) and [pino-http](https://github.com/pinojs/pino-http)
- [x] I couldn't find the same [question about nestjs-pino](https://github.com/iamolegga/nestjs-pino/issues?q=label%3Aquestion)
- [x] This is not a question about how to use this library with pino-_transport-name-goes-here_

**Question**

I'm trying to migrate away from Winston but I can't seem to manage to run multiple streams in Pino with NestJS.

I've read all the docs and looked around for answers but I can either find only relevant things for multi-streams outstide of NestJS 

All I'm trying to do is to store the logs in a file in JSON format and to output to the console using pino-pretty so that I can still get human readable logs in console but with the ability to read the JSON formatted logs using a GUI log reader.

**Please mention other relevant information such as Node.js version and Operating System.**
Node v20.5.0
Debian 12.4

**Comment by iamolegga** [comment]
This question is not related to the current library. This is a tiny wrapper for pino library, it just passes pino config as it is.

You should try to implement this with a basic logging script without any server and after just copy your settings properly to the current library. Pino docs have an example of multiple transports: https://getpino.io/#/docs/transports?id=writing-to-a-custom-transport-amp-stdout 

Closing

**Comment by sardortaylakov** [comment]
@palbrecht1 see if this is useful: https://github.com/sardortaylakov/nestjs-pino-logstash/blob/main/src/app.module.ts#L37-L51
