### ISSUE TITLE
[BUG] "is not a function" when trying to extend PinoLogger

### ISSUE THREAD

**Issue by lookto** [iamolegga/nestjs-pino#1869]
- [X] I've read [the docs of nestjs-pino](https://github.com/iamolegga/nestjs-pino/blob/master/README.md)
- [X] I've read [the docs of pino](https://getpino.io/#/) and [pino-http](https://github.com/pinojs/pino-http)
- [X] I couldn't find the same [open issue of nestjs-pino](https://github.com/iamolegga/nestjs-pino/issues)
- [ ] This bug is related only to current library or I've tested the same behaviour with the built-in logger and this is not a bug of NestJS.

**What is the current behavior?**
When trying to extend the PinoLogger like descriped in the docs ([Link](https://github.com/lookto/custom-nestjs-pino-logger)) things are not exactly working. If I try to add a new function and call it in a service, typescript tells me that it's not a function.

Also if I try to overwrite the .info() function to add additional logic this is never called. In the reproduction repo thats a simple additional console.log, but in production this should be more complex. 

My assumption is, that the logger instance in the AppService is off PinoLogger and not the CustomLoggerService.

Am I doing something wrong?

```
// logger.module.ts
import { Module } from '@nestjs/common';
import { LoggerModule as PinoLoggerModule } from 'nestjs-pino';
import { CustomLoggerService } from './logger.service';

@Module({
  exports: [CustomLoggerService],
  providers: [CustomLoggerService],
  imports: [
    PinoLoggerModule.forRoot({
      pinoHttp: {
        level: 'debug',
        autoLogging: false,
        serializers: {
          /* eslint-disable @typescript-eslint/no-empty-function */
          req: () => {},
          /* eslint-disable @typescript-eslint/no-empty-function */
          res: () => {},
        },
        transport: {
          target: 'pino-pretty',
          options: {
            colorize: true,
          },
        },
      },
    }),
  ],
})
export class CustomLoggerModule {}

// logger.service.ts
import { Injectable } from '@nestjs/common';
import { PinoLogger } from 'nestjs-pino';

@Injectable()
export class CustomLoggerService extends PinoLogger {
  info(msg: string) {
    console.log('This is a test!');
    super.info(msg);
  }

  log(msg: string) {
    console.log(msg);
  }
}

// app.module.ts
import { Module } from '@nestjs/common';
import { AppController } from './app.controller';
import { AppService } from './app.service';
import { CustomLoggerModule } from './logger/logger.module';

@Module({
  imports: [CustomLoggerModule],
  controllers: [AppController],
  providers: [AppService],
})
export class AppModule {}

// app.service.ts
import { Injectable } from '@nestjs/common';
import { InjectPinoLogger } from 'nestjs-pino';
import { CustomLoggerService } from './logger/logger.service';

@Injectable()
export class AppService {
  constructor(
    @InjectPinoLogger(AppService.name)
    private readonly logger: CustomLoggerService,
  ) {}

  getHello(): string {
    this.logger.info('Hello World');
    this.logger.log('Custom logger function');
    return 'Hello World!';
  }
}

```

**What is the expected behavior?**
I can add custom functions to the extended PinoLogger and extend/overwrite PinoLogger functions like .info(), .error() etc.

**Please provide minimal example repo, not code snippet. Without example repo this issue will be closed.**
https://github.com/lookto/custom-nestjs-pino-logger

**Please mention other relevant information such as Node.js version and Operating System.**
NodeJS: v20.11.0
PNPM: 8.15.1

**Comment by iamolegga** [comment]
I'm not sure about this part: `@InjectPinoLogger(AppService.name)`, I assume that you are injecting not your custom logger but the original one

**Comment by lookto** [comment]
> I'm not sure about this part: `@InjectPinoLogger(AppService.name)`, I assume that you are injecting not your custom logger but the original one

Thanks for rubberducking my code. You are absolutly right, I don't know why I never considered that. I guess I need to set the context in another way.
