### ISSUE TITLE
[QUESTION] How to import LoggerModule from another module

### ISSUE THREAD

**Issue by fneiraj** [iamolegga/nestjs-pino#1879]
- [x] I've read [the docs of nestjs-pino](https://github.com/iamolegga/nestjs-pino/blob/master/README.md)
- [x] I've read [the docs of pino](https://getpino.io/#/) and [pino-http](https://github.com/pinojs/pino-http)
- [ ] I couldn't find the same [question about nestjs-pino](https://github.com/iamolegga/nestjs-pino/issues?q=label%3Aquestion)
- [x] This is not a question about how to use this library with pino-_transport-name-goes-here_

**Question**

Hello, I am creating a base library for my nestjs services, in which I am creating a LoggerModule that imports the LoggerModule of nestjs-pino, if I use it in the same project it works OK, but if I create it as a library and try to use it From this, it gives me the following error:

Error: Nest could not find Logger element (this provider does not exist in the current context)

my loggerModule:

```
import { Module } from '@nestjs/common';
import { LoggerModule as LM } from 'nestjs-pino';

@Module({
  imports: [
    LM.forRoot(),
  ],
})
export class LoggerModule { }
```

Is there a way to externalize the LoggerModule from nestjs-pino?

**Please mention other relevant information such as Node.js version and Operating System.**

node: v20.10.0

**Comment by iamolegga** [comment]
Hello, I've got the idea, but I'm not sure why it doesn't work. Maybe in your reusable module, you could either export a configuration for logger or export a built module like: `export const LoggerModule = LM.forRoot(...)`. Does it make any sense?

**Comment by fneiraj** [comment]
It didn't work either :(, I also realized that if I import the LoggerModule (nestjs-pino) and then my library module in which I use the '@nestjs/common' logger, it ignores the pine one and does it with the default from nestjs, any idea why this happens? (in the app code it uses the pine one but in the library code it uses the nest default)

**Comment by iamolegga** [comment]
Sorry, but it's hard to debug by github comments. Minimal example should be added to answer you question properly

**Comment by fneiraj** [comment]
my-common-library:

```
import { Module } from '@nestjs/common';
import { HealthModule } from './health';
import { LoggerModule } from 'nestjs-pino';

@Module({
  imports: [
    LoggerModule
      .forRoot
      //my default config for logger
      (),
    HealthModule, //imports health module with a simple /health
  ],
  controllers: [],
  providers: [],
})
export class CommonsModule {}
```

build and add to another project with npm install ../my-common-library or npm link, and add import CommonsModule:

```
import { Module } from '@nestjs/common';
import { AppController } from './app.controller';
import { AppService } from './app.service';
import { CommonsModule } from 'my-common-library';

@Module({
  imports: [CommonsModule], //import common module from library
  controllers: [AppController],
  providers: [AppService],
})
export class AppModule {}
```

I configure the nestjs logger for the app in main.ts:

```
import { NestFactory } from '@nestjs/core';
import { AppModule } from './app.module';
import { PinoLogger } from 'nestjs-pino';

async function bootstrap() {
  const app = await NestFactory.create(AppModule);
  app.useLogger(app.get(PinoLogger)); // error here
  await app.listen(3000);
}
bootstrap();
```

If I comment the logger setup line it works and loads the /health module correctly

**Comment by fneiraj** [comment]
I also tried to load the LoggerModule directly in the app without going through the library, which works, but the logs that are inside the library are executed with the nest logger and not with pino

**Comment by fneiraj** [comment]
I added MyLogger in the library and I am loading it with NestFactory.create(AppModule, { logger: new MyLogger() });, it loads it only in the MyApp files but not in the library files, from what I see it is something of nestjs then or the way I'm adding the library

<img width="625" alt="image" src="https://github.com/iamolegga/nestjs-pino/assets/50465935/68ce6ccb-c760-49ab-9385-9fb9cf0a3921">

**Comment by fneiraj** [comment]
I did a quick test by uploading the library to npm and adding it to myapp from npm and it works fine, apparently it's something in the way I install it locally for development, thank you very much anyway, I'm closing the issue.

**Comment by joshmeads** [comment]
@fneiraj are you using `pnpm`? I'm having a similar issue and can't figure out why...

I created a new app using the CLI in monorepo mode. pnpm as the installer and following the basic examples I get the following message:
```
Nest could not find Logger element (this provider does not exist in the current context)
```
