### ISSUE TITLE
[BUG] Incorrect Cyrillic symbols in the log

### ISSUE THREAD

**Issue by zanchess** [iamolegga/nestjs-pino#1924]
- [x] I've read [the docs of nestjs-pino](https://github.com/iamolegga/nestjs-pino/blob/master/README.md)
- [x] I've read [the docs of pino](https://getpino.io/#/) and [pino-http](https://github.com/pinojs/pino-http)
- [x] I couldn't find the same [open issue of nestjs-pino](https://github.com/iamolegga/nestjs-pino/issues)
- [x] This bug is related only to current library or I've tested the same behaviour with the built-in logger and this is not a bug of NestJS.

**What is the current behavior?**
I'm trying to log messages with Cyrillic symbols `this.logger.log('Мой лог')` I see incorrect symbols in the log.
Example log:
![image](https://github.com/iamolegga/nestjs-pino/assets/46690347/50c2199e-dfa3-4db9-a078-53b044b6f2eb)

**What is the expected behavior?**
Message 'Мой лог' instead of ╨Ь╨╛╨╣ ╨╗╨╛╨│

**Please provide minimal example repo, not code snippet. Without example repo this issue will be closed.**
Link on my [code](https://github.com/zanchess/nest-temp/blob/80f1693d96be1628348db24b693fee7510e14dd6/backend/src/module/common/apiConfig/apiConfig.service.ts#L41)

**Please mention other relevant information such as Node.js version and Operating System.**
Node version: 20, OS: Windows 11

**Comment by iamolegga** [comment]
this is an issue with pino, not nestjs-pino which is just a wrapper

**Comment by iamolegga** [comment]
https://getpino.io/#/docs/help?id=unicode-and-windows-terminal
