### ISSUE TITLE
[QUESTION] Is there a way to log function start and end automatically

### ISSUE THREAD

**Issue by amit12cool** [iamolegga/nestjs-pino#199]
Is there a way nestjs-pino supports automatically logging function start and end along with function arguments.
I just want to avoid tedious work of adding a info log in each function everytime.

**Comment by iamolegga** [comment]
No, there is not for now. Do you want this feature to be realised as some decorator for service/service method?

**Comment by amit12cool** [comment]
Yes, would be great?

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

________________________________

**Comment by iamolegga** [comment]
Yep, I think this could be useful. Can you open feature request please with described details, and I'll try to find time for this, or maybe someone else could see this and dive into it faster than me

**Comment by amit12cool** [comment]
Done!.
