### ISSUE TITLE
[BUG] Only the first argument is printed

### ISSUE THREAD

**Issue by andrew-sol** [iamolegga/nestjs-pino#2004]
- [x] I've read [the docs of nestjs-pino](https://github.com/iamolegga/nestjs-pino/blob/master/README.md)
- [x] I've read [the docs of pino](https://getpino.io/#/) and [pino-http](https://github.com/pinojs/pino-http)
- [x] I couldn't find the same [open issue of nestjs-pino](https://github.com/iamolegga/nestjs-pino/issues)
- [ ] This bug is related only to current library or I've tested the same behaviour with the built-in logger and this is not a bug of NestJS.

**What is the current behavior?**

The following code:
```ts
this.logger.log('foo', { bar: 'baz' }, 'baf');
```
prints only the first argument and ignores the rest.

I have 1 project where it works well and 2 projects where it does not. And I have no idea why.
I cloned this repo into my project and debugged the code till this line:
```ts
// PinoLogger.ts
this.logger[method](...args);
```
all the arguments are present here, but only the first one is logged.

If I remove this line from the `main.ts` file:
```ts
app.useLogger(app.get(Logger));
```
then the default NestJS logger logs all 3 arguments. But when I turn on the Pino logger again, it does not work.

**What is the expected behavior?**

All the arguments should be logged.

Reproduction repo: https://github.com/andrew-sol/nestjs-pino-reproduction

**Comment by iamolegga** [comment]
built-in logger and pino have different notations, see examples here or in pino docs

**Comment by andrew-sol** [comment]
I see, thank you.

I will link some of the related issues here:
#961
#1271

So, basically, this library cannot be used as a drop-in replacement for the native NestJS's Logger class (which is sad).

I created a gist with the logger class that can be used as a drop-in replacement for the default Nest's logger and supports nestjs-pino (it does not support Pino's interpolation though): https://gist.github.com/andrew-sol/3d47976fdb8213347e8f50d5a73f984c

**Comment by iamolegga** [comment]
@andrew-sol correct, all the log messages should be updated when moving to this library

**Comment by yamcodes** [comment]
I am working on a fork designed to be a drop-in replacement for NestJS's logger: https://github.com/yamcodes/pino-nestjs

```ts
// With nestjs-pino (Pino style):
this.logger.log({ foo: 'bar' }, 'Hello World');

// With pino-nestjs (NestJS style):
this.logger.log('Hello World', { foo: 'bar' });
```

**Comment by mlvl42** [comment]
I recently discovered that pino introduced hooks that can be used to change the order of the arguments, this way both logging styles should work

```typescript
import pino from 'pino';

function swapMessageAndObject(args: unknown[], method: pino.LogFn) {
  if (args.length >= 2 &&
      typeof args[0] === 'string' &&
      typeof args[1] === 'object' &&
      !Array.isArray(args[1])) {
    const [msg, obj, ...rest] = args;
    return method.apply(this, [obj as object, msg, ...rest]);
  }
  return method.apply(this, args);
}

const pinoInstance = pino({
  level: process.env.LOG_LEVEL || 'info',
  hooks: { logMethod: swapMessageAndObject },
  transport: getTransportConfig(),
  base: { service: 'api' },
});
```

**Comment by iamolegga** [comment]
Soon (next couple of weeks) I'm planning to release a new version with Logger class to use in `app.useLogger(...)` that will work same as a native nestjs one. So, for existing projects that want to move to this lib it will be easier to do it, and for new projects there will be an option which of logger styles to choose

**Comment by Timur2915** [comment]
@iamolegga any updates? We currently use our own hook for this and would love to drop it.
