### ISSUE TITLE
[QUESTION] Hello, I just want to record incorrect requests.  All manually printed logs are recorded. Is there any good way

### ISSUE THREAD

**Issue by gexin1** [iamolegga/nestjs-pino#2123]
- [x] I've read [the docs of nestjs-pino](https://github.com/iamolegga/nestjs-pino/blob/master/README.md)
- [x] I've read [the docs of pino](https://getpino.io/#/) and [pino-http](https://github.com/pinojs/pino-http)
- [x] I couldn't find the same [question about nestjs-pino](https://github.com/iamolegga/nestjs-pino/issues?q=label%3Aquestion)
- [ ] This is not a question about how to use this library with pino-_transport-name-goes-here_

**Question**

**Please mention other relevant information such as Node.js version and Operating System.**

**Comment by iamolegga** [comment]
Didn't get the question
