### ISSUE TITLE
[FEATURE REQUEST] Support autoLogging ignorePaths feature of pino-http

### ISSUE THREAD

**Issue by arvinsingla** [iamolegga/nestjs-pino#237]
**Is your feature request related to a problem? Please describe.**
The [latest version](https://github.com/pinojs/pino-http/pull/77) of pino-http (`4.4.0`) includes a new param for autoLogging called ignorePaths which allows you to specify an array of paths to ignore. We need this to prevent logging for our health-check endpoints.

There are two issues I discovered when trying to see if I could get this working with nestjs-pino.

1. The typescript definitions for `pino-http` haven't been updated to include this new option. I have created a pull request to add it here (https://github.com/DefinitelyTyped/DefinitelyTyped/pull/43137)

2. The [underlying pino-http feature](https://github.com/pinojs/pino-http/blob/master/logger.js#L73) uses the `req.url` property to compare against the configured ignore paths. This is a problem because `req.url` in nest class middlewares gets rewritten with the route mount point stripped. So it is always `/`  regardless of which route is hit. I believe this is a byproduct of how `app.use()` works in express  

**Describe the solution you'd like**
Somehow figure out how this feature could be implemented.

**Describe alternatives you've considered**
As a more proactive measure I've put up a PR against `pino-http` that if accepted would make this feature request irrelevant. It would allow for us to specify the current path through a function passed as an `autoLogging` option. This would allow us to use req.originalUrl instead of req.url. https://github.com/pinojs/pino-http/pull/80

**Comment by iamolegga** [comment]
Good, thank for your work! 👍

**Comment by iamolegga** [comment]
Hi, I see now that https://github.com/pinojs/pino-http#api is updated. So are we good now and I can close this issue, or we need to update something?

**Comment by arvinsingla** [comment]
I think we can close this request. We are still waiting for them to put out a new release that includes the changes, but when they do the current package.json rules in this project should pick it up.

**Comment by iamolegga** [comment]
Good, thank you very much for your work! This is very important feature 👍
