### ISSUE TITLE
[QUESTION] Is posible disable the request logger middleware?

### ISSUE THREAD

**Issue by gperdomor** [iamolegga/nestjs-pino#253]
Hi... Is possible toggle on/off the request logger?

**Comment by iamolegga** [comment]
Hi, if you need to prevent request/response log and you DO NOT want to use logger in current route, you can do this via [config params](https://github.com/iamolegga/nestjs-pino#configuration-params) (`forRoutes`, `exclude`)

if you need to prevent request/response log and you DO want to use logger in current route you can look at [API of related library](https://github.com/pinojs/pino-http#api) (`autoLogging`, `autoLogging.ignorePaths`), which params is passed via `pinoHttp`

**Comment by iamolegga** [comment]
Also see [this comment](https://github.com/iamolegga/nestjs-pino/issues/237#issuecomment-607800046) in another issue, seems like it is not shipped now, but may be soon

**Comment by gperdomor** [comment]
@iamolegga even when use forRoute and exclude to disable the route logging, the middleware is still configured, so in this particular case when I want exclude all routes, the middleware is not necessary...

**Comment by iamolegga** [comment]
@gperdomor Excuse me, I didn't get it, what is your case?

**Comment by gperdomor** [comment]
@iamolegga don't worry... In my case, I only want to use the logger service, not the middleware...

Here is where the middleware is registered... Maybe one parameter `middleware: boolean` should be sufficient to enable or disable the middleware https://github.com/iamolegga/nestjs-pino/blob/d338c54f6c4c06ce1ea69f00805eb75344c00c1c/src/LoggerCoreModule.ts#L67

**Comment by iamolegga** [comment]
Got you, sorry, but middleware is required, because it creates `logger` object which is used internally by Logger/PinoLogger, so yes, you can rely on `autoLogging`/`autoLogging.ignorePaths` properties of `pinoHttp` object of params.

Just saw, that new pino-http's types are shipped already, so you can wait for new release with this soon

**Comment by iamolegga** [comment]
check out v1.2.0

**Comment by btilford** [comment]
Does the request logging work with fastify? I can't seem to get a configuation that will do access/error logs or include the request id in general logging throughout a request.

**Comment by iamolegga** [comment]
> Does the request logging work with fastify?

It should, if it's not please provide example repo with bug

**Comment by btilford** [comment]
> > Does the request logging work with fastify?
> 
> It should, if it's not please provide example repo with bug

I think the issue is with express-ctx, the middleware doesn't seem to be running on fastify. 

https://github.com/btilford/nestjs-pino-fastify-bug

I was able to hack around it by writing custom middleware, express-ctx isn't doing very much either. If you used cls-hooked directly I think nestjs-pino could also work for lambdas or cloud functions where you have an invocation id.

**Comment by gowrav-scienaptic** [comment]
Exception thrown when using `nestjs-pino` with FastifyAdapter.

```
(node:85089) UnhandledPromiseRejectionWarning: TypeError: Unexpected MODIFIER at 3, expected END
    at mustConsume (/backend/node_modules/middie/node_modules/path-to-regexp/dist/index.js:113:15)
    at parse (/backend/node_modules/middie/node_modules/path-to-regexp/dist/index.js:172:9)
    at stringToRegexp (/backend/node_modules/middie/node_modules/path-to-regexp/dist/index.js:329:27)
    at pathToRegexp (/backend/node_modules/middie/node_modules/path-to-regexp/dist/index.js:403:12)
    at Object.use (/backend/node_modules/middie/engine.js:23:16)
    at Object.use (/backend/node_modules/middie/index.js:30:21)
    at /backend/node_modules/@nestjs/platform-fastify/adapters/fastify-adapter.js:130:27
    at MiddlewareModule.registerHandler (/backend/node_modules/@nestjs/core/middleware/middleware-module.js:138:9)
    at MiddlewareModule.bindHandler (/backend/node_modules/@nestjs/core/middleware/middleware-module.js:96:25)
    at async /backend/node_modules/@nestjs/core/middleware/middleware-module.js:84:13
```

@btilford, Can you please post the custom middleware you used to bypass this issue.

**Comment by btilford** [comment]
@gowrav-scienaptic So I basically setup NestJS middleware instead of express middleware.

```typescript
import {setValue} from 'express-ctx/dist';
import {middleware as ectx} from 'express-ctx';

// Middleware to create the logger
app.use((req, res, next) => {

    if (req.url.match(options.accessLogIgnore)) {
      const phto: Options = options.pinoHttpOptions.pinoHttp as Options;
      const copy: Options = clone<Options>(phto);
      copy.autoLogging = false;
      pinoHttp(copy)(req, res);
    }
    else {
      pinoHttp({
        ...options.pinoHttpOptions.pinoHttp as pinoHttp.Options,
      })(req, res);
    }
    next();
  });

  // Middleware to add the logger to the context. This part isn't ideal and should just use `cls-hooked` but does work.
  app.use((req, res, next) => {

    ectx(req, res, () => {
      // Make the logger available to PinoLogger's
      setValue(LOGGER_KEY, req.log);
      next();
    });
  });
```

**Comment by gowrav-scienaptic** [comment]
@btilford, Thank you for the response. On debugging my issue, I found that using nestjs-pino with `app.setGlobalPrefix('api');` throws the `UnhandledPromiseRejectionWarning`.

**Comment by alexeychikk** [comment]
@gowrav-scienaptic https://github.com/nestjs/nest/issues/5568#issuecomment-708510442
