### ISSUE TITLE
[FEATURE REQUEST]

### ISSUE THREAD

**Issue by mbreton** [iamolegga/nestjs-pino#264]
**Is your feature request related to a problem? Please describe.**
I'm looking for a way to add the Application name into each log.

**Describe the solution you'd like**
I would like a new parameter in forRoot module method in order to give an App name.

**Describe alternatives you've considered**
I would like to get access to Pino instance logger used in the module in order to create a child logger with this property.  This option is maybe more powerful.

**Additional context**
This kind of information is especially useful when a save all the logs of all micro-services in the same space.

**Comment by iamolegga** [comment]
Hi, you can do this via [mixin method](https://github.com/pinojs/pino/blob/master/docs/api.md#mixin-function). Just pass it to `pinoHttp` property.

[More about `pino` API](https://github.com/pinojs/pino/blob/master/docs/api.md#api)
[More about `pino-http` API](https://github.com/pinojs/pino-http#api)

**Comment by mbreton** [comment]
You know how to talk to me. 🖖

Thank you for your quick answer!
