### ISSUE TITLE
[FEATURE REQUEST] Customize requests messages

### ISSUE THREAD

**Issue by na-ji** [iamolegga/nestjs-pino#265]
Hello,

**Is your feature request related to a problem? Please describe.**
I would like the ability to customize the messages automatically logged by `pino-http` (`request completed` and `request errored`).

**Describe the solution you'd like**
Since version 5.0.0 of `pino-http`, two new options were added: `customSuccessMessage` and `customErrorMessage` to do this. So in the end my feature request is only updating the dependencies and publishing a new version. However, the types package is not up to date, so it might not be possible right now.

**Describe alternatives you've considered**
I haven't considered any alternative yet.

**Additional context**
Nothing to add.

Thank you!

**Comment by iamolegga** [comment]
Thanks, if you are ready to monitor for typings you can ping me when it's done or even create PR by yourself 👍

**Comment by iamolegga** [comment]
Hey @na-ji pino-http@5 and it's types are [merged in master](https://github.com/iamolegga/nestjs-pino/blob/master/package.json#L34-L36) and shipped in `1.2.0`. So I'm closing this
