### ISSUE TITLE
[FEATURE REQUEST] Support GCP logging

### ISSUE THREAD

**Issue by Mistic92** [iamolegga/nestjs-pino#290]
**Is your feature request related to a problem? Please describe.**

Is it possible to support GCP logging like they have integration with [Bunyan ](https://github.com/googleapis/nodejs-logging-bunyan)and [Winston](https://github.com/googleapis/nodejs-logging-winston)?

When using pino on GCP I see that it's formating logs well to make them supported in Stackdriver and Logging but it's not setting Trace field:( Also there is option to support logs related to request with section "Formatting Request Logs"

**Describe the solution you'd like**
**Describe alternatives you've considered**

**Additional context**

**Comment by iamolegga** [comment]
Hi, this question is not related to `nestjs-pino` because this is only wrapper for `pino` with some framework's specific.

But, I googled and found [pino-stackdriver](https://github.com/pinojs/pino/blob/master/docs/transports.md#pino-stackdriver). I think this is what you are looking for

**Comment by Mistic92** [comment]
Thank you
