### ISSUE TITLE
Log to FILE or DB

### ISSUE THREAD

**Issue by BooNoo** [iamolegga/nestjs-pino#300]
Hello!

How can I implement log to file or database?

I use global log as bellow:

async function bootstrap() {
    const app = await NestFactory.create(AppModule, {
        logger: false,
    });
    app.useLogger(app.get(Logger));
    await app.listenAsync(process.env.PORT || 3000);
}

bootstrap().then();

**Comment by iamolegga** [comment]
Hi, https://getpino.io/#/docs/transports
