### ISSUE TITLE
[QUESTION] How to log the res.body

### ISSUE THREAD

**Issue by Jeff-Tian** [iamolegga/nestjs-pino#303]
By default, only `responseTime`, `statusCode` and `headers` are logged.

```
"res":{"statusCode":304,"headers":{...}},"responseTime":15
```

Is there a configuration to enable logging res.body?

**Comment by iamolegga** [comment]
[There is example](https://github.com/pinojs/pino-http#logger-options) how to provide custom serializers to `pino-http`, which params you must pass to `pinoHttp` property of `nestjs-pino` [configuration params](https://github.com/iamolegga/nestjs-pino#configuration-params)

**Comment by Jeff-Tian** [comment]
Thanks, by following your provided link, found there is an exact example to log request's body here:

https://github.com/pinojs/pino-http/pull/76/files

**Comment by khalilchoudhry** [comment]
@Jeff-Tian your initial question was about how to log response body on request completion not about request body log. have you figured out how to log response body from our API

I havent been able to log the response body yet. I still get:
`"res":{"statusCode":304,"headers":{...}},"responseTime":15`

@iamolegga tried your mentioned example as well for plain express based app with follow serializers:
`
serializers: {
    err: pino.stdSerializers.err,
    req: pino.stdSerializers.req,
    res: pino.stdSerializers.res
  },
`
&
`
serializers: {
res: (res) => {
      res.body = res.body;
      return res;
    }
}
`

example response from API I am using:

`return res.status(http_status.OK).send(data);`

**Comment by skliarovartem** [comment]
it is so strange to don't show response body. in case of security you need just exclude rout...
so, if there a way to simply print response body?

**Comment by iamolegga** [comment]
> it is so strange to don't show response body

@skliarovartem nothing strange. response body can be huge, can have sensitive data, can be of a binary type, the current default behaviour is better than anything else.

 > so, if there a way to simply print response body?

this question should be asked in `pino-http` library, not here, this is just a wrapper with nestjs related features

**Comment by Milan4e** [comment]
Response body is still not shown in logger.

**Comment by gaurav1999** [comment]
In, case if you are working with Fastify, you have to first register the prehandler hook

ref: https://fastify.dev/docs/latest/Reference/Logging
```
app = await NestFactory.create<NestFastifyApplication>(AppModule, new FastifyAdapter({ logger: true }));
      app.getHttpAdapter().getInstance().addHook('preHandler', (request, reply, done) => {
        if (request.body) {
          request.log.info({ body: request.body })
        }
        done();
      });

```

**Comment by ZauJulio** [comment]
After a few hours I managed to do it, here are the specs and an example of how to replicate it:

```ts
import { LoggerModule } from 'nestjs-pino';
import { pino } from 'pino';

import { MiddlewareConsumer, Module } from '@nestjs/common';
import { ConfigModule, ConfigService } from '@nestjs/config';
import { AuthModule } from './auth/auth.module';
import { LogRequestBodyMiddleware } from './logger.middleware';

@Module({
  imports: [
    ConfigModule.forRoot({
      isGlobal: true,
    }),
    AuthModule,
    LoggerModule.forRootAsync({
      imports: [ConfigModule.forRoot({ isGlobal: true })],
      useFactory: async (configService: ConfigService) => ({
        pinoHttp: {
          level: process.env.LOG_LEVEL ?? 'trace',
          redact: {
              paths: [
                  'password',
                  'reqBody.password',
                  'user.password',
                  'reqBody.user.password',
            ],
          },
          transport: {
            timestamp: pino.stdTimeFunctions.isoTime,
            targets: [
              {
                level: process.env.LOG_LEVEL ?? 'trace',
                target: 'pino-pretty',
                options: {
                  colorize: true,
                  singleLine: true,
                  translateTime: "yyyy-mm-dd'T'HH:MM:ss.l'Z'",
                  ignore: 'pid,hostname',
                  minimumLevel: 'info',
                  errorLikeObjectKeys: ['err', 'error'],
                },
              },
              {
                target: 'pino/file',
                level: process.env.LOG_LEVEL ?? 'trace',
                options: { destination: `${__dirname}/../../app.log` },
              },
            ],
          },
        },
      }),
      inject: [ConfigService],
    }),
  ],
  providers: [],
  controllers: [],
})
export class AppModule {
  configure(consumer: MiddlewareConsumer) {
    consumer.apply(LogRequestBodyMiddleware).forRoutes('*');
  }
}
```

- LogRequestBodyMiddleware

```ts
import { Injectable, Logger, NestMiddleware } from '@nestjs/common';
import { randomUUID } from 'crypto';
import { Request, Response, NextFunction } from 'express';

@Injectable()
export class LogRequestBodyMiddleware implements NestMiddleware {
  private readonly logger = new Logger();

  use(req: Request, res: Response, next: NextFunction) {
    const _id = randomUUID();

    res.setHeader('X-Request-Id', _id);
    this.logger.log({ [_id]: req.body });

    next();
  }
}
```
