### ISSUE TITLE
[QUESTION] Usage with pino-caller

### ISSUE THREAD

**Issue by matomesc** [iamolegga/nestjs-pino#306]
I would like to use [pino-caller](https://github.com/pinojs/pino-caller) to log the line number where the log method was invoked. Is it currently possible to use the returned `pino-caller` logger instance when configuring this module?

**Comment by iamolegga** [comment]
You can see example of passing specific logger instance [here](https://github.com/iamolegga/nestjs-pino#extreme-mode). But I'm not quite sure if this will work for you, because logger methods are called via wrapper class, but you can try anyway

**Comment by matomesc** [comment]
Thanks! Sadly I wasn't able to get it to work because `pino-caller` proxies only certain methods to the underlying logger and `child` is not one of them (this module needs it) - this can easily be fixed in `pino-caller`, however we also need to fix the the stack trace to account for the added frames by `nestjs-pino`. I will give this a try and report back.
