### ISSUE TITLE
[QUESTION] How to use Pino for entire application with configuration options?

### ISSUE THREAD

**Issue by humbertowoody** [iamolegga/nestjs-pino#330]
Hi!

First of all, thanks for this module, it is really appreciated.

I am trying to use Pino Logger throughout the application; perhaps I am wrong about it, but what I am doing is to add the following code to `app.module.ts`:

```typescript
@Module({
    imports: [
        ConfigModule.forRoot(),
        LoggerModule.forRoot({
            pinoHttp: { prettyPrint: true, useLevelLabels: true }, // <--
        }),
        // ...
    ],
    // ...
})
export class AppModule {}
```
And, in `main.ts`:

```typescript
import { NestFactory } from '@nestjs/core';
import { Logger } from 'nestjs-pino';

async function bootstrap() {
  // Create the application.
  const app = await NestFactory.create(AppModule, { logger: false });

  // Get Pino Logger instance.
  const logger = app.get(Logger);

  // Use Pino as the main logger!
  app.useLogger(logger);

  // Start the server!
  await app.listen(3030);
}

// Initialize application!
bootstrap();
```

The issue is that, if I import `LoggerModule` and call `forRoot` (or `forRootAsync` by injecting `ConfigService` etc), *without* any Pino options (`prettyPrint` or `useLevelLabels`) it works perfectly, however when adding even one option, it hangs the entire application without even booting! 

1. Is this the way to use the Logger throughout the Application?
2. If it is, am I providing configuration options in a wrong format?

I would like to use Pino as the main logging system for the entire application, no exclusions.

I am using NestJS v7.

Again, thanks for this library! And thanks in advance for any commentary this might receive :)

**Comment by iamolegga** [comment]
Hi, it's very interesting, could you create some mini example repo for that?

**Comment by humbertowoody** [comment]
Sure! Thanks for your quick response :)
https://github.com/humbertowoody/example-pino-nestjs

This is the most simple case I can come around.

**Comment by iamolegga** [comment]
Thanks, I'll look at it in next couple of days

**Comment by iamolegga** [comment]
Hey @humbertowoody just found the problem. When using `prettyPrint` property you need extra installation of `pino-pretty` as it said in [docs](http://getpino.io/#/docs/api?id=prettyprint-boolean-object) 🙂

**Comment by humbertowoody** [comment]
Thank you very much @iamolegga !
Sorry to miss that part of the docs! Guess I just read this package ones and not the pino itself ones! Really sorry about this.
Thanks for quick response and guidance :)
