### ISSUE TITLE
[QUESTION] How can I retrieve the 'req.id' from each request?

### ISSUE THREAD

**Issue by Somya-Bansal** [iamolegga/nestjs-pino#340]
I have a microservice architecture, where all external requests are http, while internal ones are gRPC. 
Now for logging, I want to have a unique id for each http request, so that I can have a correlation between my logs in different microservices.

Is there a way to retrieve the 'req.id', so that I can provide it as metadata in my clientGrpc call?

**Comment by iamolegga** [comment]
does it solve your issue https://docs.nestjs.com/controllers#request-object ?

**Comment by skliarovartem** [comment]
Did you find how to pass and get id's from service to service by transporters?

**Comment by antspk** [comment]
I'm actually searching for a solution myself, So far this is what I've come up: 

I've created a separate service which is bound to request scope: 
```typescript
export class ReqIdService {
  constructor(private readonly request: Request) {}

  getReqId(): string {
    return (this.request as unknown as { id: string }).id;
  }
}
```

And the add that service to container:
```typescript
import { REQUEST } from '@nestjs/core';

@Module({
  providers: [
    {
      provide: ReqIdService,
      useFactory: (req) => new ReqIdService(req),
      inject: [REQUEST],
      scope: Scope.REQUEST,
    },
  ],
})
```
After that you can inject that service wherever you need and retrieve req id of that request.

Haven't properly tested it yet though I've got this idea from the suggestion of:
https://docs.nestjs.com/controllers#request-object
And a similar issue:
https://stackoverflow.com/questions/54979729/howto-get-req-user-in-services-in-nest-js

They key here is that pino request id once created is added to request object.
