### ISSUE TITLE
[BUG] When context is supplied to Logger, message gets stringified

### ISSUE THREAD

**Issue by mayorandrew** [iamolegga/nestjs-pino#353]
**What is the current behavior?**

Recommended way to use nestjs logger is to instantiate the singleton class `Logger` from `@nestjs/common` and supply context to it (https://stackoverflow.com/a/52907695/4601673), like so:

```
import { Logger } from '@nestjs/common';

class MyService implements OnModuleInit {
  logger = new Logger(MyService.name);
  onModuleInit() {
    this.logger.log({ msg: 'test' });
  }
}
```

Using this pattern with nestjs-pino works quite well, but there is a catch.
When context is supplied, message is sent as a second argument to pino here: https://github.com/iamolegga/nestjs-pino/blob/master/src/Logger.ts#L35.
This results in message being treated as the format string here: https://github.com/pinojs/pino/blob/master/lib/tools.js#L52.
So if message is an object, it gets stringified into the "msg" field of the logged json object, like so:
```
{"level":30,"time":1598681218911,"pid":92,"hostname":"sse-sandbox-hxfsk","context":"AppService","msg":"{\"msg\":\"test\"} "}
```

If context is not supplied, the message is supplied as the first argument and pino correctly logs the message as an object.

**Please provide the steps to reproduce.**

Here is the minimal codesandbox based on nestjs-typescript-starter with pino-logger applied and used from AppService.
https://codesandbox.io/s/nestjs-pino-logger-context-forked-hxfsk?file=/src/app.service.ts

There are some issues with displaying logging output though :(

**What is the expected behavior?**

I expect message to be logged the same way it is logged when context is not supplied (i.e. merged into root object), like so:
```
{"level":30,"time":1598681218911,"pid":92,"hostname":"sse-sandbox-hxfsk","context":"AppService","msg":"test"}
```

**Please mention other relevant information such as Node.js version and Operating System.**

I do not think this is relevant, but I am using node v12.18.2 and OS Windows 10 Pro 2004.

**P.S.**

If this is not an intended behavior, I can make a PR to fix it by merging message into context object in all of the methods of `Logger` class. I would also like to add this usage example to the documentation.

**Comment by iamolegga** [comment]
Hello, thanks for such detailed explanation.

> I can make a PR to fix

yes, please, feel free to open pr, I'll try to review it as soon as possible, but please add test for both cases: when `msg` is object and string, or you can ask for my help with tests, if you'll need it 👍

**Comment by iamolegga** [comment]
Just looked again at error example. It use mix of both loggers (original nestjs one and one from current library), so that's not how it's supposed to be used. There is only one way to use this library: `Logger` or `PinoLogger` only.

Current implementation of `Logger` from this package can not be used so far as in provided example from stackoverflow. If you still need this, feel free to open feature request for that or better PR.

For now I'm closing this bug as it's not expected usage of library, but feel free to continue discussion if you have more questions. Thanks

**Comment by mayorandrew** [comment]
Yeah, it was not obvious for me also, but I digged quite a lot and it now seems logical to me. Here is my reasoning:

NestJS somehow supports replacing the default logger with a custom logger via `app.useLogger`. Since NestJS actively uses DI, changing the logger should not affect any of the other classes, but it should be a simple substitution of the service provider. I.e. in the app I should just use some kind of "abstract" logger, agnostic of the implementation. So if I use `app.useLogger` to globally change the implementation of the logger, the need to inject a different interface to my services seems counter-intuitive to me. Nestjs docs are not super clear about that, so I started googling. 

One of my key requirements was that I should be able to easily supply context to the logger. If I inject `Logger` from pino, I cannot use `setContext` on it (there is no such method in `Logger` despite the fact that it is defined in the `LoggerService` interface which it implements), so I have to supply context in each log message, or write some kind of wrapper. Also since, logger provider has singleton scope, calling mutating `setContext` on it is kinda strange. And because of my idea about implementation agnosticity, I do not want to use `PinoLogger` interface and would like to stay as close to nestjs as possible.

I found this post this post on SO: https://stackoverflow.com/a/52907695/4601673. And didn't get how that could possibly work. I tried it and was happy that it works and I could finally supply the context for each of my services in a convenient way and stay implementation-agnostic in my app services. So nestjs somehow uses the logger I supplied to `app.useLogger` when I use the `Logger` from `@nestjs/common`. 

So I digged through the source. If we look how `app.useLogger` is implemented (https://github.com/nestjs/nest/blob/67e15afbf33364ac6dcf0ade58d26aade7c2eb1f/packages/core/nest-application-context.ts#L123), it actually calls static method `Logger.overrideLogger` of the `Logger` from `@nestjs/common` which changes the static property `Logger.instance` (https://github.com/nestjs/nest/blob/01dfe29458a2851e42efe8d5b4d614caf9935742/packages/common/services/logger.service.ts#L70).

Now, if we look, how `Logger` itself is implemented, whenever you call instance methods like `log`/`warn`, it actually calls the related method from the saved `Logger.instance` (https://github.com/nestjs/nest/blob/01dfe29458a2851e42efe8d5b4d614caf9935742/packages/common/services/logger.service.ts#L108).

Basically, calling `app.useLogger` is useless if you do not use `Logger` from `@nestjs/common`. If we dig more into nestjs source code, the logger is actually used the same way, as provided in the SO anwser, so I think that is how it should be. Basically nestjs itself and possible third-party libraries would just use `Logger` from `@nestjs/common` and assume its implementation agnosticity.
Here are some examples: https://github.com/nestjs/nest/blob/fc05b244a8a0db15ef60e612c9e2afe0290f995a/packages/core/errors/exception-handler.ts#L5, https://github.com/nestjs/nest/blob/eedd9df6e42aa035d14c2e861f401269d26d4d4f/sample/27-scheduling/src/tasks/tasks.service.ts#L6

That is quite a strange way of orchestrating the logging, but that is what Nestjs have. So in my opinion, ideal logging library would be a plug'n'play substitution for the existing Logger interface, instead of forcing user to inject a different interface to their own services.

Maybe if you do not fancy changing the existing `Logger` class, we can add a new class, which is supposed to be used the way I described.

**Comment by iamolegga** [comment]
Ok, got you. So here we have 2 options:

- add one more class for using it only on `app.useLogger` level
- change existing `Logger` class, that would be breaking change, and that should be covered in docs along with benefits of it and migration to new version (change usages to original class). Also we should check codebase and update tests, examples etc. 

I'm leaning towards the latter, because I don't want to grow the size of this library. So now I suggest you to open new feature request issue with detailed list of things that should be done, and then you can update your PR and I'll reopen it

**Comment by mayorandrew** [comment]
Thanks for the understanding. I also think the the second option if better in the long term.
Maybe we can create some transient `Logger` provider for the old logger interface to smooth out the transition and mark it deprecated. It will use the new mechanics under the hood, but API will remain close to the original.

Will be glad to help by making a new feature request and updating my PR. Just in case, I think it will take couple of weeks before I can find enough spare time for that.

**Comment by iamolegga** [comment]
> Maybe we can create some transient Logger provider for the old logger interface to smooth out the transition. We could mark it deprecated so it is obviously legacy

I think that's unnecessary. I think that the best way to deal with migrating to original class is create codemod, but that could be challenging.

> Just in case, I think it will take couple of weeks before I can find enough spare time for that.

feel free to open it as you will be ready 🙂
