### ISSUE TITLE
[QUESTION] How to log req.id only?

### ISSUE THREAD

**Issue by purefun** [iamolegga/nestjs-pino#372]
It's overloaded to log `req` object with every log. Is there a way to just print `req.id` only? 
Of course, the  `pinoHttp.autoLogging` should be turned on. the `request completed` log and `error` logs should contain `req` and `req` completely.
Thanks in advance.

**Comment by purefun** [comment]
`pino-http` [attaches](https://github.com/pinojs/pino-http/blob/master/logger.js#L100) the `PinoLogger` instance to `req.log`, and logger service methods are delegated to it. I can't find a direct way to achieve my goal.

**Comment by iamolegga** [comment]
Sorry, I'm not quite sure I understand the question. Is it correct that it's more about `pino-http` than `nestjs-pino`?

**Comment by purefun** [comment]
When call `nestjs-pino` logger service, like `logger.log('something')`, it will print:
```json
{ "message": "something", "req": { "id": 1 } }
```
The `req.id` is generated by `pino-http`.

Cause `nestjs-pino`'s loggerService calls the log created by `pino-http` `(log.child({ req })` eventually, I think there is no way to control it.

**Comment by iamolegga** [comment]
I think this could be a feature request at `pino-http`. It's already have `reqCustomProps`, which is close to feature you need
