### ISSUE TITLE
[QUESTION] How to inject nestjs-pino logger into Module configuration?

### ISSUE THREAD

**Issue by ErolPeel** [iamolegga/nestjs-pino#373]
I am new to NestJS and NodeJS. I am using `nestjs-pino` in my application.

In my `AppModule` class I am importing the `LoggerModule`. Then when I configure `TypeOrmModule` I want to log something with `nestjs-pino`. How can I inject the  `nestjs-pino` logger into my module configuration?

```typescript
@Module({
  imports: [
    LoggerModule.forRoot({
      pinoHttp: {
        autoLogging: false
      }
    }),
    TypeOrmModule.forRootAsync({
      useFactory: async () => {
        const host = process.env.DATABASE_HOST || "localhost";
        const port = Number(process.env.DATABASE_PORT) || 5432;
        const username = process.env.DATABASE_USER || "postgres";
        const password = process.env.DATABASE_PASSWORD || "mysecretpassword";
        const database = process.env.DATABASE_DATABASE || "postgres";
        // TODO use nestjs-pino here
        console.log(`Connecting to database ${database} on ${host}:${port} with user ${username}`);
        return {
          type: "postgres", host: host, port: port, username: username, password: password, database: database, synchronize: true
        };
      }
    })
  ],
  controllers: [AppController, HealthController],
  providers: [AppService]
})
export class AppModule {
}
```

**Comment by iamolegga** [comment]
do it just as any other provider, see example from official docs: https://docs.nestjs.com/fundamentals/custom-providers#factory-providers-usefactory

just add `inject` field type of array, that will go to your factory arguments

for injecting this lib to factory you can add `inject:[Logger]` or `inject:[PinoLogger]` (both imported from current package)
