### ISSUE TITLE
[QUESTION] customize pino parameters

### ISSUE THREAD

**Issue by Code2Life** [iamolegga/nestjs-pino#38]
In some cases, we need to customized pino/pino-http default params. How to configure default options globally like this?

`
{
  genReqId: generateLogId,  //pino-http ID generation
  
  prettyPrint: isDevMode ? { colorize: true } : undefined // dev env pino-pretty
}
`

**Comment by iamolegga** [comment]
If you store `isDevMode` as variable (not as property of some `ConfigService`) see https://github.com/iamolegga/nestjs-pino#synchronous-configuration, it should work.

If you depend on some `ConfigService` see https://github.com/iamolegga/nestjs-pino#asynchronous-configuration

**Comment by Code2Life** [comment]
Got.. Thanks a lot, sorry for missing the document
