### ISSUE TITLE
[QUESTION] Extend PinoLogger class

### ISSUE THREAD

**Issue by alexabidri** [iamolegga/nestjs-pino#391]
Hi guys! I would like to extend the Pino logger to be able to inject my own business logic in some cases (for example logger.error).

So decided to build a logger module on top of nestjs-pino.

Here are my two files

**logger.service.ts**

```js
import { Injectable } from '@nestjs/common';
import { PinoLogger } from 'nestjs-pino';

@Injectable()
export class LoggerService extends PinoLogger {
  error(message: any, trace?: string, context?: string, ...args: any[]) {
    // My business logic here
    super.error(message, trace);
  }
}
```

**logger.module.ts**

```js
import { Global, Module } from '@nestjs/common';
import { LoggerService } from './logger.service';
import { LoggerModule as PinoModule } from 'nestjs-pino';

@Global()
@Module({
  imports: [PinoModule.forRoot()],
  providers: [LoggerService],
  exports: [LoggerService],
})
export class LoggerModule {}
```

I am importing the module in app.module.ts.
My issue is when I start the application, I got this error at module initialization.

```
Error: Nest can't resolve dependencies of the LoggerService (?). Please make sure that the argument pino-params at index [0] is available in the LoggerModule context.

Potential solutions:
- If pino-params is a provider, is it part of the current LoggerModule?
- If pino-params is exported from a separate @Module, is that module imported within LoggerModule?
  @Module({
    imports: [ /* the Module containing pino-params */ ]
  })
```

I cannot figured out why I have this message, I am well imported the PinoModule in the loggerModule.

Thanks for any help :smile_cat:

**Comment by pablo-w-dev** [comment]
+1

**Comment by iamolegga** [comment]
Hi, easiest way is composition here, but if you want extend it please provide minimal repo for that without business logic as in your example above, I could take a look at it

**Comment by alexabidri** [comment]
Thanks @iamolegga , here is the repo where you can find the simple logger module with controller "Hello World"

**Comment by iamolegga** [comment]
Thanks, I'll try to find time for this in a week

**Comment by orzarchi** [comment]
any updates regarding this? I'd also like to add some logic to `logger.error` (sending errors to Sentry)

**Comment by iamolegga** [comment]
@orzarchi this can be done with current implementation, see docs of this lib and https://github.com/aandrewww/pino-sentry#usage

**Comment by AckerApple** [comment]
I arrived at this issue needing to override pino and extend it's functionality.... I have since solved my issue and here is my working override code to that makes the root pino give me override access:


**TypeScript**
```
import pino from 'pino'
const myPino = pino()
const orgChildMethod = myPino.child
myPino.child = function(this: any, details: any) {
  const newPino = orgChildMethod.call(this, details)
  newPino.info = function(logMeta: any): void {
    logger.info({...logMeta, ...details}) // our custom override
  }
  newPino.warn = function(logMeta: any): void {
    logger.warning({...logMeta, ...details}) // our custom override
  }
  return newPino
}
```

**JavaScript**
```
const myPino = require('pino')()
const orgChildMethod = myPino.child
myPino.child = function(details) {
  const newPino = orgChildMethod.call(this, details)
  newPino.info = function(logMeta) {
    logger.info({...logMeta, ...details}) // our custom override
  }
  newPino.warn = function(logMeta) {
    logger.warning({...logMeta, ...details}) // our custom override
  }
  return newPino
}
```

**Comment by dguyonvarch** [comment]
This error is due to `pino-params` provider which is not exported by the module : https://github.com/iamolegga/nestjs-pino/blob/master/src/LoggerCoreModule.ts#L61

Any way to exported it ? I would like to extends `Logger` too...

**Comment by iamolegga** [comment]
@dguyonvarch feel free to open pr for this

**Comment by jdt6** [comment]
until PR gets merged, @iamolegga, or @dguyonvarch  what is the work around for adding a wrapper around the Logger?

**Comment by AckerApple** [comment]
Look in the comments @jdt6 I posted a working solution in both TypeScript and JavaScript

**Comment by iamolegga** [comment]
closed in #441

**Comment by delai** [comment]
@AckerApple how can i use the code, run the code in every nestjs controller or service? is there any  elegant way?

**Comment by AckerApple** [comment]
@delai I have copy, pasted, and edited the clean solution we have been running on several projects.

Good luck reading out the details, I just quick and dirty got you the bulk of our solution

```ts
import { Module, Logger } from '@nestjs/common'
import { LoggerModule } from 'nestjs-pino'
import pino from 'pino'

@Module({
  controllers: [],
  providers: [ Logger ],
  imports: [
    LoggerModule.forRoot({
      pinoHttp: {
        enabled: true,
        logger: getOurPino(logger), // see function below for details
      }
    })
  ],
})
export default class AppModule {
}

/** Pino logger functionality override to report to us instead of console
 * We use pino to ensure request.id in every log.
 * It has a child recursive nature to it that makes overrides a bit complex
 * FUTURE: belongs in shared for transactions repo (requires pino package dep management)
*/
export function getOurPino(
   logger: any // We want Pino to call something else for every log (our internal logging tool)
): pino.Logger {
  const myPino = pino()
  const orgChildMethod = myPino.child
  myPino.child = function(this: any, details: any) {
    const newPino = orgChildMethod.call(this, details)

    /* customs overrides */
      newPino.info = function(logMeta: any): void {
        logger.info({...logMeta, ...details})
      }

      newPino.warn = function(logMeta: any): void {
        logger.warning({...logMeta, ...details})
      }

      newPino.error = function(logMeta: any): void {
        logger.error({...logMeta, ...details})
      }

      newPino.debug = function(logMeta: any): void {
        logger.debug({...logMeta, ...details})
      }
    /* end: custom overrides */

    return newPino
  }

  return myPino
}
```

**Comment by iamolegga** [comment]
@AckerApple may I ask you why an extension of `PinoLogger` doesn't fit for you?

> Pino logger functionality override to report to us instead of console

you can pass [transports](https://getpino.io/#/docs/transports) as a [`pinoHttp.stream`](https://github.com/pinojs/pino-http#pinohttpopts-stream) field of module settings. But I personally prefer to pipe stdout to the transport in that case

**Comment by AckerApple** [comment]
@iamolegga im on v6 and seems that’s a v7 feature

I will look to check it out

**Comment by condef5** [comment]
@AckerApple in this part
```
       logger: getOurPino(logger), // see function below for details
```

where does this `logger` variable come from?

**Comment by AckerApple** [comment]
The short: We have our own company logger so we pass that in there.

The long: “getOurPino()” as seen above, essentially takes Pino logs and casts them to fit our needed format. So the argument “logger” is what our company passes in and one main difference is our company logger uses “warning” instead of “warn” but thats the flexibility we get with “getOutPino()”. So if you needed to cast Pino logs to something of your own format, then copy “getOurPino()” and edited it to your needs.

The data typing for logger, instead of any, should be:
```ts
logger: {
  info: (…args: any[]) => any,
  warning: (…args: any[]) => any,
  debug: (…args: any[]) => any,
  error: (…args: any[]) => any,
}
```
