### ISSUE TITLE
[FEATURE REQUEST] Get access to method `isLevelEnabled`

### ISSUE THREAD

**Issue by bervol** [iamolegga/nestjs-pino#404]
I am using NestJS, pino and nestjs-pino.

Normally, I am injecting the `PinoLogger` like this to log my statements:
```typescript
import { PinoLogger } from "nestjs-pino";
```

However, now I want to access the method [`logger.isLevelEnabled(level)`](https://github.com/pinojs/pino/blob/master/docs/api.md#islevelenabled). `Unfortunately`, PinoLogger does not have this method.

How can I access `isLevelEnabled` with nestjs-pino?

**Comment by iamolegga** [comment]
Unfortunately not implemented yet. I'll convert this to feature request

**Comment by iamolegga** [comment]
closed in #439
