### ISSUE TITLE
[QUESTION] Is it possible to redact certain JSON keys from logging?

### ISSUE THREAD

**Issue by nmjmdr** [iamolegga/nestjs-pino#409]
I was wondering if it is possible to redact certain JSON keys from request logging and logging? Pino has support for redaction, but I could not see a Param for redaction in nestjs-pino.

**Comment by iamolegga** [comment]
could you please add more details and references, unfortunately question is not clear for me

**Comment by nmjmdr** [comment]
Example of redaction in pino: [Redaction in Pino](https://github.com/pinojs/pino/blob/master/docs/redaction.md)

I was wondering if this is possible in nestjs-pino

**Comment by iamolegga** [comment]
The answer is in [docs](https://github.com/iamolegga/nestjs-pino#configuration-params):

```ts
interface Params {
  /**
   * Optional parameters for `pino-http` module
   * @see https://github.com/pinojs/pino-http#pinohttpopts-stream
   */
  pinoHttp?:
    | pinoHttp.Options
    | DestinationStream
    | [pinoHttp.Options, DestinationStream];
  ...
}
```

https://github.com/pinojs/pino-http#pinohttpopts-stream:

> it has all the options as pino and ...

**Comment by hliang** [comment]
not sure anything has changed, but i tried recently and just need to set the `pinoHttp.redact` property. No need to provide a pino logger instance.
```javascript
pinoHttp: {
  redact: ['req.headers.authorization', 'req.headers.cookie']
}
```

**Comment by mtubul** [comment]
is it working you? i try it out but the fields are not redacted
this is my code 
```LoggerModule.forRoot({
      pinoHttp: {
        redact: ['req.headers.authorization', 'req.headers.cookie'],
        transport: {
          target: 'pino-pretty',
          options: {
            singleLine: true,
            translateTime: 'SYS:standard',
            ignore: 'pid,res,hostname,req',
          },
        },
        level: process.env.LOG_LEVEL || 'warn',
      },
    }),```
