### ISSUE TITLE
[QUESTION] Log level when using as NestJS app logger

### ISSUE THREAD

**Issue by navmed** [iamolegga/nestjs-pino#411]
I'd like to use this as a NestJS app logger as described here: https://github.com/iamolegga/nestjs-pino#usage-as-nestjs-app-logger

How can I specify the log levels and other configuration?

**Comment by iamolegga** [comment]
You can specify log levels via configuration of LoggerModule: https://github.com/iamolegga/nestjs-pino#asynchronous-configuration please see https://github.com/iamolegga/nestjs-pino#configuration-params for more details

**Comment by dlecan** [comment]
Is it `level` or `useLevel`?

From https://github.com/iamolegga/nestjs-pino#asynchronous-configuration
```
         pinoHttp: { level: config.level },
```

From https://github.com/pinojs/pino-http#pinohttpopts-stream
```
...
useLevel: the logger level pino-http is using to log out the response. default: info
...
```

**Comment by iamolegga** [comment]
@dlecan this two different options

> `useLevel`: the logger level pino-http is using to log out the response. default: info

`level` sets level for logger, so only logs with level >= options.level will be emitted. I recommend read the docs of `pino` first

**Comment by twelve17** [comment]
Also worth noting, the NestJS `repl` [uses its own logger](https://github.com/nestjs/nest/blob/master/packages/core/repl/repl.ts#L18), so the pino logging config does not seem to be used (and hence any logger that might have been specified in that config.)
