### ISSUE TITLE
[QUESTION] Use a custom wrapper class to log requests to files

### ISSUE THREAD

**Issue by dadooda** [iamolegga/nestjs-pino#434]
Hi guys,

I want the following setup for my NestJS application:

1. HTTP requests are logged to a dedicated file, using `nestjs-pino`. They'll be sent to the ELK logging facilities by Filebeat or whatever.
2. Additionally, `Logger` Pino object is available for manual invocation across the project (`this.logger.log("...")`).
3. Default NestJS stdout logger is enabled.

How do I achieve that?

Say, I let the "middleware" thing initialize like this:

```ts
@Module({
  imports: [ LoggerModule.forRoot({ autologging: false, pinoHttp: { ... } }) ],
  ...
})
export class AppModule {}
```

Is there a way I can re-create the middleware manually, where I can use my custom class (as per NestJS documentation) which in turn uses Pino logger configured by the `LoggerModule`, but directs its output to a file?

Thank you very much.

**Comment by iamolegga** [comment]
Sorry, I didn't get the question, if you need some kind of transport you can look at [pino docs](https://getpino.io/#/). If that's not what you want, please try to explain in other words

**Comment by dadooda** [comment]
Please delete this. It's indeed confusing.

Thanks for getting in touch.
