### ISSUE TITLE
[BUG] `genReqId` in `pinoHttp` configuration does nothing

### ISSUE THREAD

**Issue by sinclairnick** [iamolegga/nestjs-pino#442]
**What is the current behavior?**

Setting the `genReqId` property to anything does not alter the `pid`.

**Please provide the steps to reproduce.**

Set `genReqId` to `(req) => "THING"`

**What is the expected behavior?**

My understanding is `genReqId` should set the `pid` property upon request, but it doesn't seem to do anything at the moment

**Please mention other relevant information such as Node.js version and Operating System.**
Using `nestjs-pino: ^1.3.0`
Using node 14

**Comment by iamolegga** [comment]
`pid` stands for _process id_.  Look at `genReqId` [here](https://github.com/pinojs/pino-http#pinohttpopts-stream).
Closing this issue, in case if this not works with `id` field in logs feel free to reopen, but please provide minimal example repo
