### ISSUE TITLE
Trace log is not working [BUG] 

### ISSUE THREAD

**Issue by Andr-07** [iamolegga/nestjs-pino#464]
**What is the current behavior?**

I am using PinoLogger in my project. Everything works fine except logs 'trace' and 'debug'.

When I do logger.info, logger.warn or logger.error I get all that logs in console, but if I want to use other methods it just doesn't print at all.

My module:
```
LoggerModule.forRoot({
      useExisting: true,
      pinoHttp: {
        ...ecsFormat(),
        prettyPrint: {
          colorize: true,
          levelFirst: true,
          singleLine: true,
        },
      },
    }),
```

**What is the expected behavior?**

I do expect printed logs with methods: trace and debug

**Please mention other relevant information such as Node.js version and Operating System.**
Node - v12.6.0

**Comment by iamolegga** [comment]
Please provide minimal example repo, also double check that you've installed [pino-pretty](https://github.com/pinojs/pino-pretty#programmatic-integration)

**Comment by Andr-07** [comment]
@iamolegga Hi, thanks for respond!

Yes, pino-pretty is installed.

My example of module:

```
import * as ecsFormat from '@elastic/ecs-pino-format';
import { Module, OnModuleDestroy, OnModuleInit } from '@nestjs/common';
import { ConfigModule, } from '@nestjs/config';
import { CronExpression } from '@nestjs/schedule';
import { CronJob } from 'cron';
import { LoggerModule, PinoLogger } from 'nestjs-pino';

// Config
import configuration from '../../../../../../../shared/config/configuration';
// Shared services
import { ShutdownService } from '../../../../../../../shared/services';
// Producer
import { AppProducer } from './app.producer';

@Module({
  imports: [
    LoggerModule.forRoot({
      useExisting: true,
      pinoHttp: {
        ...ecsFormat(),
        prettyPrint:{
                colorize: true,
                levelFirst: true,
                singleLine: true,
       },
     }
    }),
    ConfigModule.forRoot({
      load: [configuration],
      isGlobal: true,
    }),
  ],
  providers: [
    // Services
    ShutdownService,
    // Producers
    AppProducer,
  ],
})
export class AppModule implements OnModuleInit, OnModuleDestroy {
  constructor(
    private readonly logger: PinoLogger,
  ) {
  }

  async onModuleInit(): Promise<void> {
    this.logger.setContext('AppModule.onModuleInit');

    this.logger.trace(`this log is not working`);
    this.logger.info(`it works fine`);
  }
}
```

Versions:

"pino-pretty": "^4.8.0",
"nestjs-pino": "^1.4.0",
"@elastic/ecs-pino-format": "^1.1.1"

**Comment by iamolegga** [comment]
@Andr-07 sorry, but this is not minimal example repo. Can you generate new nestjs project with [nest generate](https://docs.nestjs.com/cli/overview#basic-workflow), add only nestjs-pino, add your minimal usecase to show the bug and push this repo, so I can clone it and check with only one command. Thanks

**Comment by Andr-07** [comment]
@iamolegga - I have generated the project - https://github.com/Andr-07/pino-logger/blob/main/src/app.module.ts



![image](https://user-images.githubusercontent.com/46841332/118376179-0e6fd580-b5cf-11eb-8078-37c55c2fe918.png)

**Comment by iamolegga** [comment]
Thanks, need time to check this

**Comment by Andr-07** [comment]
@iamolegga

Hi, I forgot to write, that found the solution: I have just added the field `level: 'trace'` in pinoHttp.

My example:

```

**Comment by iamolegga** [comment]
Ah, of course, levels 😀ok, closing this

**Comment by prufrock123** [comment]
@iamolegga - I might suggest reopening this? I am using the customLogLevel method from the README and all the levels work except for trace (which behaves just like 'silent').

To reproduce, just run the code used in the README but use `trace` instead of `info`:
https://github.com/pinojs/pino-http#logger-options

**Comment by iamolegga** [comment]
@prufrock123 please open a new issue with the minimal example repo
