### ISSUE TITLE
[QUESTION] How do I get request/response auto logging with Fastify and pinoHttp custom config?

### ISSUE THREAD

**Issue by drxwskx** [iamolegga/nestjs-pino#467]
[x] I've read [the docs of nestjs-pino](https://github.com/iamolegga/nestjs-pino/blob/master/README.md)

[x] I've read [the docs of pino](https://getpino.io/#/)

[x] I couldn't find the same [question about nestjs-pino](https://github.com/iamolegga/nestjs-pino/issues?q=label%3Aquestion)

**Question 
I've configured nestjs-pino on my nestjs project and everything seems to be working correctly with all the default settings. Except when I want to configure pino to have more human-readable logs in development suddenly I no longer get request/response auto logging. 

How do I get request/response auto logging with Fastify and pinoHttp custom config?

Here's my custom configuration in my root module
```javascript
    LoggerModule.forRootAsync({
      imports: [ConfigModule.forFeature(nodeConfig)],
      inject: [nodeConfig.KEY],
      useFactory: async ({ environment }: ConfigType<typeof nodeConfig>) => {
        return {
          pinoHttp: {
            autoLogging: true,
            formatters: {
              level: (levelLabel, levelNumber) => ({
                log: levelLabel,
                level: levelNumber,
              }),
            },
            useLevel:
              environment === NodeEnvironment.PRODUCTION ? 'info' : 'debug',
            prettyPrint: environment !== NodeEnvironment.PRODUCTION && {
              colorize: true,
              translateTime: true,
            },
          },
        };
      },
    })
```
When I remove the `pinohttp` configuration object from the return statement in the `useFactory` method the auto-logging works. 

And here's main.ts setup as well. 
```javascript
  const app = await NestFactory.create<NestFastifyApplication>(
    AppModule,
    new FastifyAdapter({ keepAliveTimeout: keepAliveTimeoutMS }),
    { logger: false },
  );
  const logger = app.get(Logger);
  app.useLogger(logger);
```

Side note the setup for Fastify isn't very clear to me from/after reading docs. Should I be passing the `{ logger: false }` option to the Fastify adapter or to the nest factory like I currently have it?

Appreciate the help! 

**Please mention other relevant information such as Node.js version and Operating System.**
Running within a docker container on a node 14.15.3 Image.

**Comment by iamolegga** [comment]
Hi, have you installed `pino-pretty`?

**Comment by iamolegga** [comment]
@drxwskx ?

**Comment by iamolegga** [comment]
no response, closing

**Comment by drxwskx** [comment]
> Hi, have you installed `pino-pretty`?

Yes, `pino-pretty` was installed...

Apologies for the late reply it was a long weekend/holiday here in Canada

**Comment by drxwskx** [comment]
Also like I mentioned the pretty print works fine but once it's enabled I no longer get auto-request / response logging which works when the pretty print is disabled.

**Comment by drxwskx** [comment]
So passing logLevel "debug" disables the auto logging

**Comment by iamolegga** [comment]
Ok no problem, reopening, but can you please create small repo with bug reproduction for me to quick jump into it? Can not help with only code samples because there are some other not related things (for example formatters, node env, and could be something more?)
