### ISSUE TITLE
[QUESTION] How I could disable log for certain hosts

### ISSUE THREAD

**Issue by felinto-dev** [iamolegga/nestjs-pino#472]
[x] I've read [the docs of nestjs-pino](https://github.com/iamolegga/nestjs-pino/blob/master/README.md)
[x] I've read [the docs of pino](https://getpino.io/#/)
[x] I couldn't find the same [question about nestjs-pino](https://github.com/iamolegga/nestjs-pino/issues?q=label%3Aquestion)

**Question**

I would know how I could ignore certain hosts to be logged.

The reason is that I have a healthcheck that tests an HTTP route every 30s, even in the development environment, and healthcheck requests pollute the console

If possible, I would a minimal code to see how is it works.

**Comment by iamolegga** [comment]
https://github.com/iamolegga/nestjs-pino/issues/253#issuecomment-616613889
https://github.com/iamolegga/nestjs-pino/issues/253#issuecomment-617432600
