### ISSUE TITLE
[QUESTION] Change the log content in runtime / or to have more loggers

### ISSUE THREAD

**Issue by michalmoravek** [iamolegga/nestjs-pino#481]
[x] I've read [the docs of nestjs-pino](https://github.com/iamolegga/nestjs-pino/blob/master/README.md)

[x] I've read [the docs of pino](https://getpino.io/#/)

[x] I couldn't find the same [question about nestjs-pino](https://github.com/iamolegga/nestjs-pino/issues?q=label%3Aquestion)

Is there a way how to change log content (amount of information) logged in each log message?

What I'm solving...

In my application I would like to have 3 categories of log messages:
- "application" log messages containing information usable for debugging or problem solving (I dont need request / response content and urls in these messages - usualy)
- "api performance" log messages containing information about request url and response time
- "audit" log messages containing information about request / response body, logged user...

Currently I have configured PinoLogger globally in my app module for "application" logs. But this logger configuration is not suitable for my "api performance" and "audit" logs.

Thanks for help.

Michal

**Comment by iamolegga** [comment]
Hi Michal

I'm not sure I get the problem you have, but you can use:

application - `Logger` or `PinoLogger`
api - don't turn off logging of request/response
audit - same `Logger` or `PinoLogger` inside controller/service when you have all the required data

**Comment by iamolegga** [comment]
No response, closing
