### ISSUE TITLE
[QUESTION] Is there any way to unbind the request/response data in regular logs?

### ISSUE THREAD

**Issue by b1acKr0se** [iamolegga/nestjs-pino#508]
- [x]  I've read [the docs of nestjs-pino](https://github.com/iamolegga/nestjs-pino/blob/master/README.md)

- [x]  I've read [the docs of pino](https://getpino.io/#/)

- [x]  I couldn't find the same [question about nestjs-pino](https://github.com/iamolegga/nestjs-pino/issues?q=label%3Aquestion)

**Question**

Basically, I want `nestjs-pino` to automatically log all requests/responses, but in regular logs (which are initiated by me) I dont want the request data to be attached to the log. Is this possible?

_In a service_

```
this.logger.log('Hello', UserService.name);
```

will output this message: (I use `prettyPrint`)

```
[08/19/2021, 13:25:23.907] INFO: [UserService] - Hello
    req: {
        .....
    },
    ....
```

But I only want this:

```
[08/19/2021, 13:25:23.907] INFO: [UserService] - Hello
```

Thank you.

**Please mention other relevant information such as Node.js version and Operating System.**

**Comment by iamolegga** [comment]
It seems like in your case this library is not required at all, and you can set up [express-pino-logger](https://github.com/pinojs/express-pino-logger) as [global middleware](https://docs.nestjs.com/middleware#global-middleware) for example. Or choose any other logger middleware

**Comment by JE-lee** [comment]
Given that the lib is built at the top of `pino-http`, you can opt out of this by passing `quietReqLogger : false`. [see also](https://github.com/pinojs/pino-http?tab=readme-ov-file#pinohttpopts-stream)
