### ISSUE TITLE
Calling this.logger.assign({"traceId":"123456"}) in a middleware throws an error

### ISSUE THREAD

**Issue by respondsid** [iamolegga/nestjs-pino#530]
A middleware (scope request) should be able to setup traceIDs and application specific context for all the loggers it will be ideal if a middleware can do it

Error throws is

:"ExceptionsHandler","msg":"PinoLogger: unable to assign extra fields out of request scope

Seems like the async local storage is initialized after all the middleware and before calling the first controller, because same call works from the controller.

**Comment by iamolegga** [comment]
Closing. Read the template guide before submitting issue @respondsid

**Comment by respondsid** [comment]
Sure can you provide the specific link please it will help

**Comment by iamolegga** [comment]
1

<img width="139" alt="image" src="https://user-images.githubusercontent.com/5501657/131562543-10960e9d-0331-4739-bc70-8862b6dcf2f4.png">

2

<img width="1153" alt="image" src="https://user-images.githubusercontent.com/5501657/131562623-3caa645a-17e5-4ece-8d1a-79e4b81ab605.png">

3

<img width="899" alt="image" src="https://user-images.githubusercontent.com/5501657/131562684-582fb674-2f30-4afd-96ef-348bd2a44acc.png">
