### ISSUE TITLE
[FEATURE REQUEST] Compatibility with pino 7 / pino-http 6

### ISSUE THREAD

**Issue by mbStavola** [iamolegga/nestjs-pino#639]
**Is your feature request related to a problem? Please describe.**

`pino-http` just dropped [version 6](https://github.com/pinojs/pino-http/releases/tag/v6.0.0) not too long ago which brings support for `pino` [7](https://github.com/pinojs/pino/releases/tag/v7.0.0).

It might be a good idea to keep up with the latest version.

**Describe the solution you'd like**

Ideally, updating to the latest with an accompanying major version bump.

**Describe alternatives you've considered**

Not updating, which is also a valid choice but would lock the library to usage with legacy `pino`.

**Additional context**

Thanks for providing such a handy library 😄

**Comment by adrianwix** [comment]
Please mention in the docs to install pino-http@5 in the meantime. I just lost some hours debugging a weird typescript error coming from the library that was not letting me compile

**Comment by iamolegga** [comment]
@mbStavola thanks for openning. Dependabot already merged the new version. I'll check this locally and add some updates to docs about `pretty-print` examples. After that will release new version

**Comment by iamolegga** [comment]
@adrianwix that's pretty strange if you have weird errors, because this package has peer deps set, so I believe you should either see warn on installing the wrong version of `http-pino` or the right version should be installed automatically if you are using the latest npm version 🤔

**Comment by iamolegga** [comment]
`2.3.0` published
