### ISSUE TITLE
[QUESTION] How to see the error stack trace?

### ISSUE THREAD

**Issue by adrianwix** [iamolegga/nestjs-pino#640]
[x ] I've read [the docs of nestjs-pino](https://github.com/iamolegga/nestjs-pino/blob/master/README.md)

[x] I've read [the docs of pino](https://getpino.io/#/)

[x] I couldn't find the same [question about nestjs-pino](https://github.com/iamolegga/nestjs-pino/issues?q=label%3Aquestion)

**Question**
How do I get to see the error stack trace?
Without that I can't really use this logger in development or production

Default Nest Logger
![image](https://user-images.githubusercontent.com/37629556/140733740-698d8dff-353b-47e7-a413-9b3d6704bd66.png)

Pino Logger
![image](https://user-images.githubusercontent.com/37629556/140733845-3b4042e1-7e0a-484e-bd78-72a65d41879b.png)

**Please mention other relevant information such as Node.js version and Operating System.**

**Comment by iamolegga** [comment]
could you please provide a minimal example repo?

**Comment by adrianwix** [comment]
Hi. I find it hard to do right now time-wise. The error came out of nestjs when using app.get() to extract a provider inside of main.ts. the message argument of Logger.call() was a string instead of an object and I guest that's why it didn't got serialized properly

**Comment by iamolegga** [comment]
it looks like you are using `pino-pretty`, right? Can this be the reason for a missing stack trace? Unfortunately, it's hard to help you without an example repo and if you are unable to provide it I'll close this issue, sorry

**Comment by adrianwix** [comment]
With pino
![image](https://user-images.githubusercontent.com/37629556/140887890-1f06170f-1a3b-4566-9aca-20b0fe1e1c73.png)

Without pino
![image](https://user-images.githubusercontent.com/37629556/140888494-b8da4a3d-03fe-436b-8e55-acd7250c1fae.png)

Repo: https://github.com/adrianwix/nestjs-pino-error

To replicate without pino just remove bufferLogs and comment out app.useLogger(app.get(Logger)) and app.flushLogs()

**Comment by adrianwix** [comment]
> it looks like you are using `pino-pretty`, right? Can this be the reason for a missing stack trace? Unfortunately, it's hard to help you without an example repo and if you are unable to provide it I'll close this issue, sorry

It doesn't show the trace even without `pino-pretty`

**Comment by iamolegga** [comment]
thanks, will check

**Comment by adrianwix** [comment]
I got this by calling `this.logger.error(Error)` directly. So in this case it works perfectly fine. The problem is that weird error from nestjs that is not an `instaceof Error` but a string.

```
[1636468442554] ERROR (3772 on LAPTOP-4EVT01A9):
    req: {
      "id": 2,
      "method": "POST",
      "url": "/tenants/cms",
      "query": {},
      "params": {
        "0": "tenants/cms"
      },
      "headers": {
        "accept": "application/json, text/plain, */*",
        "content-type": "application/json;charset=utf-8",
        "user-agent": "axios/0.21.1",
        "content-length": "477",
        "host": "localhost:2828",
        "connection": "close"
      },
      "remoteAddress": "::ffff:127.0.0.1",
      "remotePort": 49860
    }
    err: {
      "type": "ForbiddenException",
      "message": "Forbidden",
      "stack":
          ForbiddenException: Forbidden
              at RoleService.upsertUserRole (C:\Users\Adrian Wix\Code\posterlab\posterlab-mvp\nest-backend\src\iam\roles\role.service.ts:185:19)
              at processTicksAndRejections (internal/process/task_queues.js:95:5)
              at TenantService.addOwnerRoleToUser (C:\Users\Adrian Wix\Code\posterlab\posterlab-mvp\nest-backend\src\tenant\tenant.service.ts:212:9)
              at TenantPostHandler.createTenant (C:\Users\Adrian Wix\Code\posterlab\posterlab-mvp\nest-backend\src\tenant\route-handlers\tenant-post.handler.ts:71:9
)
              at TenantPostHandler.handle (C:\Users\Adrian Wix\Code\posterlab\posterlab-mvp\nest-backend\src\tenant\route-handlers\tenant-post.handler.ts:42:9)
              at TenantController.createTenantCMS (C:\Users\Adrian Wix\Code\posterlab\posterlab-mvp\nest-backend\src\tenant\tenant.controller.ts:107:24)
              at C:\Users\Adrian Wix\Code\posterlab\posterlab-mvp\nest-backend\node_modules\@nestjs\core\router\router-execution-context.js:46:28
              at C:\Users\Adrian Wix\Code\posterlab\posterlab-mvp\nest-backend\node_modules\@nestjs\core\router\router-proxy.js:9:17
              at C:\Users\Adrian Wix\Code\posterlab\posterlab-mvp\nest-backend\node_modules\@nestjs\core\router\router-explorer.js:238:17
      "response": {
        "statusCode": 403,
        "message": "Forbidden"
      },
      "status": 403,
      "name": "ForbiddenException"
    }

```

**Comment by iamolegga** [comment]
Just spent some time investigating this behavior, I believe we can close this issue because it has the same reason as the older one #535. Will add some notes soon
