### ISSUE TITLE
[BUG] 

### ISSUE THREAD

**Issue by hakanaku1234** [iamolegga/nestjs-pino#652]
[x] I've read [the docs of nestjs-pino](https://github.com/iamolegga/nestjs-pino/blob/master/README.md)

[x] I've read [the docs of pino](https://getpino.io/#/)

[x] I couldn't find the same [open issue of nestjs-pino](https://github.com/iamolegga/nestjs-pino/issues)

**What is the current behavior?**
can't build in every tags and branchs

**What is the expected behavior?**
build successfully
 
**Please provide minimal example repo. Without it this issue will be closed**
no code modified
```sh
git clone https://github.com/iamolegga/nestjs-pino.git
cd nestjs-pino
yarn && yarn build
```
**Please mention other relevant information such as Node.js version and Operating System.**

it responsed very very very long error messages about Module '"pino"' has no exported members ...

and I had already entered the "pino" index folder, there are no exported scopes that import this projects.

can not understand why and how to import those unexported members ?

I wonder how to build this project successfully, thanks.

**Comment by iamolegga** [comment]
Didn't get, do you want to use this as a dependency for your project or you want to build this project locally (then where are you trying to export something)? closing this issue, no example of bug provided

**Comment by chrapek** [comment]
For future readers: 
If you encounter errors like:
```
Namespace '"/node_modules/pino/pino"' has no exported member 'BaseLogger'.
Namespace '"/opt/pubnub-actions-service/node_modules/pino/pino"' has no exported member 'Logger'.
Module '"pino"' has no exported member 'DestinationStream'. Did you mean to use 'import DestinationStream from "pino"' instead?
```

You probably miss `"skipLibCheck": true` in tsconfig.json in your nest.js app.

I think nest-cli when creating an app with nest.js version <7 weren't adding this. Did it change since 8+ probably?
Not sure if this is a problem in `nestjs-pino` package or not tho.
