### ISSUE TITLE
[BUG] nestjs graphql use fastify and autologging feature did't work

### ISSUE THREAD

**Issue by aikin-vip** [iamolegga/nestjs-pino#698]
[ ✅  ] I've read [the docs of nestjs-pino](https://github.com/iamolegga/nestjs-pino/blob/master/README.md)

[ ✅  ] I've read [the docs of pino](https://getpino.io/#/)

[ ✅  ] I couldn't find the same [open issue of nestjs-pino](https://github.com/iamolegga/nestjs-pino/issues)

**What is the current behavior?**

**What is the expected behavior?**

**Please provide minimal example repo. Without it this issue will be closed**
[sandbox use express](https://codesandbox.io/s/wonderful-dust-lxfqp) this is fine
[sandbox use fastify](https://codesandbox.io/s/weathered-tdd-fn4ze) this is broken
**Please mention other relevant information such as Node.js version and Operating System.**

**Comment by iamolegga** [comment]
I can see auto logs in both of them
