### ISSUE TITLE
[BUG] error in initializing pino - has no exported member 'BaseLogger'

### ISSUE THREAD

**Issue by nitsanbs** [iamolegga/nestjs-pino#707]
[X] I've read [the docs of nestjs-pino](https://github.com/iamolegga/nestjs-pino/blob/master/README.md)

[X] I've read [the docs of pino](https://getpino.io/#/)

[X] I couldn't find the same [open issue of nestjs-pino](https://github.com/iamolegga/nestjs-pino/issues)

**What is the current behavior?**
I followed the guide and added imported `LoggerModule.forRoot(...)` in the root module. 
Even without using it yet (setting the app logger or using it in other modules), I get an error when running the app - 
```
node_modules/nestjs-pino/PinoLogger.d.ts:3:38 - error TS2694: Namespace '"/Users/nitsan/projects/hepius/node_modules/pino/pino"' has no exported member 'BaseLogger'.

3 declare type PinoMethods = Pick<pino.BaseLogger, 'trace' | 'debug' | 'info' | 'warn' | 'error' | 'fatal'>;
```

**What is the expected behavior?**
running without errors :)

**Please provide minimal example repo. Without it this issue will be closed**
This error also happened in a hello-world example project I tried using - 
https://github.com/manjufy/nest-hello-world
What I did was only running `npm i nestjs-pino pino-http`
and changing the to : 
```
import { Module } from '@nestjs/common';
import { AppController } from './app.controller';
import { AppService } from './app.service';
import { ItemsModule } from './items/items.module';
import { UsersModule } from './users/users.module';
import { LoggerModule } from 'nestjs-pino';


@Module({
  imports: [LoggerModule.forRoot(), ItemsModule, UsersModule],
  controllers: [AppController],
  providers: [AppService],
})
export class AppModule {}
```

**Please mention other relevant information such as Node.js version and Operating System.**
nestjs-pino - v2.3.1
node.js - v14.18.0
OSX: 10.15.7 
nestjs - 8.1.2

Thanks!

**Comment by micalevisk** [comment]
You can add `"skipLibCheck": true` under `"compilerOptions"` of your `tsconfig.json`.

But also

![image](https://user-images.githubusercontent.com/13461315/145255791-5a235d40-e700-49f8-8ba8-af66a8f76e74.png)

so you must upgrade `@nestjs/*` packages to ^8.0.0 or `npm install nestjs-pino@^1`

**Comment by iamolegga** [comment]
thanks @micalevisk 

also:

<img width="843" alt="image" src="https://user-images.githubusercontent.com/5501657/145271721-7d0d9852-61f0-4af5-bd62-3cc95f12355c.png">

types of pino/pino-http moved from separate package to main lib, but there were breaking changes. I hope will be fixed soon
