### ISSUE TITLE
[QUESTION] How to properly use transport

### ISSUE THREAD

**Issue by Lucky38i** [iamolegga/nestjs-pino#737]
[x] I've read [the docs of nestjs-pino](https://github.com/iamolegga/nestjs-pino/blob/master/README.md)

[x] I've read [the docs of pino](https://getpino.io/#/)

[x] I couldn't find the same [question about nestjs-pino](https://github.com/iamolegga/nestjs-pino/issues?q=label%3Aquestion)

**Question**

So from the looks of it, multiple targets within a transport is the ideal way to get your logged outputted to multiple areas, say STDOUT and a file. I've been attempting to do this all day scanning the docs of this package and the pino docs as-well however, I keep ending up with the same issue.

Below is how I'm configuring the parameters of the LoggerModule
<img width="1190" alt="Screenshot 2021-12-21 at 21 50 17" src="https://user-images.githubusercontent.com/26572019/147002004-165586ac-f828-492b-a944-927fa4a98451.png">

However whenever running my service I continue getting this error.
<img width="1241" alt="Screenshot 2021-12-21 at 21 51 32" src="https://user-images.githubusercontent.com/26572019/147002118-70a05752-3035-4ded-8120-2dd8d1ff29b5.png">

Maybe something is going completetly over my head here. It'd be great if you guys could help me out.

**Please mention other relevant information such as Node.js version and Operating System.**
MacOS `Big Sur 11.6.1`
node `v16.1.0`
pino-http `v6.5.0`
pino-pretty `v7.3.0`
nestjs-pino `2.4.0`

**Comment by iamolegga** [comment]
I'm not really sure, but maybe there should be a leading slash in the `destination` property? you cant try to make this work with raw express/fastify server and then copy config to nest. I'm sorry, I can not help, you can try to read the docs on certain transport or ask this question there. I've had experience only using transports as a separate process with piping stdout of main process to transport's process.

Closing as this is a question about particular transport not this lib

**Comment by iamolegga** [comment]
Maybe this lib could help you somehow https://github.com/pinojs/pino-multi-stream

**Comment by ducva** [comment]
it seems related to this one: https://github.com/pinojs/pino/issues/1278
I tried to downgrade to version 2.3.1 which used older version of `pino` and it works.

**Comment by Lucky38i** [comment]
It looks like it's fixed in `pino` is it possible to create a PR to update the version of pino used? @iamolegga

**Comment by iamolegga** [comment]
@Lucky38i This lib doesn't have deps, only [peer deps](https://github.com/iamolegga/nestjs-pino/blob/master/package.json#L88-L90). You can update `pino-http` on your own with proper `pino` version

**Comment by Lucky38i** [comment]
> @Lucky38i This lib doesn't have deps, only [peer deps](https://github.com/iamolegga/nestjs-pino/blob/master/package.json#L88-L90). You can update `pino-http` on your own with proper `pino` version

Thanks, appreciate the quick replies happy holidays
