### ISSUE TITLE
[Daily log rotation]

### ISSUE THREAD

**Issue by riteshkhatri** [iamolegga/nestjs-pino#744]
[ ] I've read [the docs of nestjs-pino](https://github.com/iamolegga/nestjs-pino/blob/master/README.md)

[ ] I've read [the docs of pino](https://getpino.io/#/)

[ ] I couldn't find the same [question about nestjs-pino](https://github.com/iamolegga/nestjs-pino/issues?q=label%3Aquestion)

**Is there a way to make Synchronous configuration With Log rotation on daily basis just like [pino] (https://github.com/pinojs/pino) supports **

Hello,
I have used nestjs pino logger with Synchronous configuration and the package is realy nice.
But i have one requirement I want to save the logs in every day new destination file which is similar to pino - log rotation (https://github.com/pinojs/pino/blob/master/docs/help.md#rotate).
Is there any way to provide support like this?

**Comment by iamolegga** [comment]
Didn't get the question. If pino supports log rotation via config, just pass it via config of current module. If you're going to do log rotation as a separate process, then there are no matter of it's nestjs server or any other. Closing, the question is not related to this lib

**Comment by subashdbc** [comment]
@riteshkhatri 
Have you found any solution for creating logs every day with nestjs-pino?
