### ISSUE TITLE
[QUESTION] (node:23332) [PINODEP008] PinoWarning: prettyPrint is deprecated

### ISSUE THREAD

**Issue by Gambitier** [iamolegga/nestjs-pino#745]
[x] I've read [the docs of nestjs-pino](https://github.com/iamolegga/nestjs-pino/blob/master/README.md)

[x] I've read [the docs of pino](https://getpino.io/#/)

[x] I couldn't find the same [question about nestjs-pino](https://github.com/iamolegga/nestjs-pino/issues?q=label%3Aquestion)

**Question**

I configured nestjs-pino with following options 

![image](https://user-images.githubusercontent.com/22792359/147587449-3b5cf7f5-a849-4c17-bd80-f4c41a31fd48.png)

and I got the warning saying
`(node:23332) [PINODEP008] PinoWarning: prettyPrint is deprecated, look at https://github.com/pinojs/pino-pretty for alternatives.`

![image](https://user-images.githubusercontent.com/22792359/147587535-58e314d6-6b47-4af8-941f-1e7b6957fd42.png)

I have following versions installed

```
"nestjs-pino": "^2.4.0",
"pino-http": "^6.5.0",
"pino-pretty": "^7.3.0",
```

**Please mention other relevant information such as Node.js version and Operating System.**

**Comment by micalevisk** [comment]
what's wrong on using the new transports API of Pino v7?

https://github.com/iamolegga/nestjs-pino#synchronous-configuration

otherwise you'll need to downgrade `nestjs-pino` to 2.3.1, I guess
