### ISSUE TITLE
HowTo setup options for nestjs-pino 

### ISSUE THREAD

**Issue by Code-Case** [iamolegga/nestjs-pino#759]
Hi,

where can I find an example for setup some options for the nestjs-pino logger?
I need for example another string for the messageKey.
Maybe Im blind but I cant find any examples.

Thank you and best regards

**Comment by iamolegga** [comment]
https://github.com/iamolegga/nestjs-pino#configuration

**Comment by Code-Case** [comment]
An example would be nicer, because there is no example for changing any options or the messageID key

**Comment by iamolegga** [comment]
@Code-Case are you kidding?

- https://github.com/iamolegga/nestjs-pino/blob/master/example/app.module.ts
- https://github.com/iamolegga/nestjs-pino#faq

Also, the issue has a template (that you've deleted for some reason) and there is a checkbox that you've read the docs before opening a new issue

**Comment by micalevisk** [comment]
> I need for example another string for the messageKey.

```ts
import * as pino from 'pino'

LoggerModule.forRoot({ pinoHttp: { logger: pino({ messageKey: 'foo' }) } })
```

most of the times you just need to play with the type defs @Code-Case
