### ISSUE TITLE
[QUESTION] Process Id is always 1? 

### ISSUE THREAD

**Issue by Shpadoinkle** [iamolegga/nestjs-pino#802]
[ * ] I've read [the docs of nestjs-pino](https://github.com/iamolegga/nestjs-pino/blob/master/README.md)

[ * ] I've read [the docs of pino](https://getpino.io/#/)

[ * ] I couldn't find the same [question about nestjs-pino](https://github.com/iamolegga/nestjs-pino/issues?q=label%3Aquestion)

**Question**
We were looking at the pid within the output examples in the docs and noticed the `pid` always changing. but noticed all our logs have a pid of 1.   Can you think of a reason for this?  Is there a function somewhere to set the process id at the start of a known flow?

**Please mention other relevant information such as Node.js version and Operating System.**

**Comment by micalevisk** [comment]
I guess this is due to which user is running your nodejs app.

btw this is related to [Pino](https://github.com/pinojs/pino), not with this repo.

**Comment by Shpadoinkle** [comment]
mmm, yea ok.  I think i see what is going on.  Thanks
