### ISSUE TITLE
[BUG] Missing nestjs/common peer dependency

### ISSUE THREAD

**Issue by atomicleopard** [iamolegga/nestjs-pino#804]
[ ✅] I've read [the docs of nestjs-pino](https://github.com/iamolegga/nestjs-pino/blob/master/README.md)

[ ✅] I've read [the docs of pino](https://getpino.io/#/)

[ ✅] I couldn't find the same [open issue of nestjs-pino](https://github.com/iamolegga/nestjs-pino/issues)

**What is the current behavior?**

The library has a peer dependency on `pino-http` but not on `@nestjs/common`. This caused an issue for us in a yarn workspace project involving nestjs@8.2.6.

Yarn workspaces hoist node modules to the root of the mono-repo when it can. Because of the missing peerDependency, yarn could hoist this library, while leaving @nestjs/common in a workspace. This causes a failure at startup because common files could not be loaded by the library.

In a typical yarn or npm install, this would not manifest because the relative directories are flat.

**What is the expected behavior?**

The library should declare all peerDependencies such that package installers understand the relationship between libraries.

**Please provide minimal example repo. Without it this issue will be closed**

https://github.com/upgrowth/repro-nestjs-pino-peer-deps

**Please mention other relevant information such as Node.js version and Operating System.**

Thanks for the library!

**Comment by iamolegga** [comment]
feel free to open PR for this

**Comment by icharge** [comment]
Please I have this problem

**Comment by iamolegga** [comment]
published in v2.5.2
