### ISSUE TITLE
[QUESTION] How to configure ECS logging format ?

### ISSUE THREAD

**Issue by BkSouX** [iamolegga/nestjs-pino#833]
[x] I've read [the docs of nestjs-pino](https://github.com/iamolegga/nestjs-pino/blob/master/README.md)

[x] I've read [the docs of pino](https://getpino.io/#/)

[x] I couldn't find the same [question about nestjs-pino](https://github.com/iamolegga/nestjs-pino/issues?q=label%3Aquestion)

**Question**

Hi,

I can't find how to configure the ECS logging format here https://github.com/elastic/ecs-logging-nodejs/tree/main/loggers/pino
Where could I set the `ecsFormat`object ? 

**Please mention other relevant information such as Node.js version and Operating System.**

**Comment by iamolegga** [comment]
<img width="562" alt="image" src="https://user-images.githubusercontent.com/5501657/154803665-99bb051f-7f59-4259-a402-fb7fdca25c58.png">

<img width="345" alt="image" src="https://user-images.githubusercontent.com/5501657/154803719-0e64bea2-10d9-4bd9-972f-09fe55934350.png">
