### ISSUE TITLE
[BUG] Request received log not logged

### ISSUE THREAD

**Issue by amit12cool** [iamolegga/nestjs-pino#895]
I have been using nestjs pino in my application and I the log for request received is not printed automatically when the request is received on a route.I have even implemented the `customReceivedMessage` function but the log is still not getting printed. Anything Im missing?

**Comment by iamolegga** [comment]
[closing](https://github.com/iamolegga/nestjs-pino/blob/master/.github/ISSUE_TEMPLATE/bug_report.md?plain=1#L10)

**Comment by amit12cool** [comment]
@iamolegga Any reason for closing this issue?

**Comment by iamolegga** [comment]
there is a link in <closing>. Don't delete the template for bug report, it's impossible to check such bug description
