### ISSUE TITLE
[QUESTION] Request received log not logged

### ISSUE THREAD

**Issue by amit12cool** [iamolegga/nestjs-pino#896]
[ -] I've read [the docs of nestjs-pino](https://github.com/iamolegga/nestjs-pino/blob/master/README.md)

[ -] I've read [the docs of pino](https://getpino.io/#/)

[- ] I couldn't find the same [question about nestjs-pino](https://github.com/iamolegga/nestjs-pino/issues?q=label%3Aquestion)

**Question**

I have been using nestjs pino in my application and I the log for request received is not printed automatically when the request is received on a route.I have even implemented the customReceivedMessage function but the log is still not getting printed. Anything Im missing?

**Please mention other relevant information such as Node.js version and Operating System.**

**Comment by iamolegga** [comment]
Sorry, I didn't get the question. Do you need automatic log when request **received**, not **completed**, because this is not how it works by default. You can check logs in example

**Comment by amit12cool** [comment]
Yes I need automatic log on request received. And this function `customReceivedMessage` is not getting called too.

**Comment by iamolegga** [comment]
please open minimal represented example repo, also check if same config works with `pino-http`

**Comment by iamolegga** [comment]
this lib is only a wrapper for `pino-http`. see the docs of it please

**Comment by iamolegga** [comment]
Closing this issue as it's a question about `pino-http` configuration. If desired behavior works with `pino-http` but not with `nestjs-pino` feel free to open a new bug report

**Comment by amit12cool** [comment]
Is it supported on the first go to print the automatic log on request received?

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________
