### ISSUE TITLE
[BUG] 2.6.0 release should be a major release

### ISSUE THREAD

**Issue by itizarsa** [iamolegga/nestjs-pino#954]
[ X ] I've read [the docs of nestjs-pino](https://github.com/iamolegga/nestjs-pino/blob/master/README.md)

[ X ] I've read [the docs of pino](https://getpino.io/#/)

[ X ] I couldn't find the same [open issue of nestjs-pino](https://github.com/iamolegga/nestjs-pino/issues)

**What is the current behavior?**
2.6.0 upgrades to pino-http@7. Which has lots of breaking changes. Refer [here](https://github.com/pinojs/pino-http/compare/v6.6.0...v7.0.0)

**What is the expected behavior?**
nestjs-pino 2.6.0 release should be released as a Major release.

**Comment by iamolegga** [comment]
> 2.6.0 upgrades to pino-http@7

@itizarsa but it [keeps](https://github.com/iamolegga/nestjs-pino/blob/master/package.json#L91)  support of previous major version of pino-http. Nothing changed for the current library and in the library API. It's up to end user which pino-http version to install as it's peer dependency
