### ISSUE TITLE
Arguments order of the logging methods

### ISSUE THREAD

**Issue by okovpashko** [iamolegga/nestjs-pino#961]
[x] I've read [the docs of nestjs-pino](https://github.com/iamolegga/nestjs-pino/blob/master/README.md)

[x] I've read [the docs of pino](https://getpino.io/#/)

[x] I couldn't find the same [question about nestjs-pino](https://github.com/iamolegga/nestjs-pino/issues?q=label%3Aquestion)

**Question**

As described in the [NestJS docs](https://docs.nestjs.com/techniques/logger#custom-implementation), the logging methods receive `message` as the first argument and the optional additional parameters (e.g . additional logging context) as the rest arguments.
I also understand that Pino uses the reverse order: the logging context (mergingObject) as the first argument and the message as the second one.

Given the fact that this library implements a custom logger for Nest.js, what's the reason for using the order of the arguments from Pino instead of a native order from Nest?
In my practice, it confuses developers who read the Nest docs and/or try to see the logging method signature in Nest's type definition and they often provide the arguments in the native Nest order that gives unexpected results in logs.

**Please mention other relevant information such as Node.js version and Operating System.**
N/A

**Comment by iamolegga** [comment]
> and the optional additional parameters (e.g . additional logging context) as the rest arguments

this was in previous major version on nest if I'm not mistaken, but now there is nothing in nest docs about context as additional argument for logging method.

> what's the reason for using the order of the arguments from Pino instead of a native order from Nest

could you please provide example for both loggers with more detailed explanation?

**Comment by okovpashko** [comment]
@iamolegga sorry for the late response.

> this was in previous major version on nest if I'm not mistaken, but now there is nothing in nest docs about context as additional argument for logging method.

You're right.

By saying `context` I mean not the class name where the logging method was called but some additional logging data such as method arguments, computation result, etc. There's nothing about it in the Nest.js docs.

In Nest.js 8 the default logger logs each of the passed arguments in a separate log record in the order they were given to a logging method.

I was confused because the Nest.js logging examples show the `message` as [the first argument](https://github.com/nestjs/nest/blob/master/packages/common/services/logger.service.ts#L13) but `nestjs-pino` follows the arguments' order from Pino and receives a message as the [second parameter](https://getpino.io/#/docs/api?id=message-string) if we want to provide any [mergingObject](https://getpino.io/#/docs/api?id=mergingobject-object).

I was expecting that `nestjs-pino` always receives a message in the first place but now understand that then it wouldn't be possible to distinguish between the merging object and interpolation values that are also supported by Pino but not by Nest.js default logger.

Seems like this issue can be closed.

**Comment by akantic** [comment]
@okovpashko did you maybe find a way to use the correct interface on the imported Logger class from Nest?

I am getting very confused by using the interface in the wrong way...

Nestjs logger interface:
```
Logger.log(message: any, context?: string | undefined): void
```

The only way to make it work correctly is calling it like this:
```
this.logger.log({ customData: 'test' }, 'real log message');
```

**Comment by iamolegga** [comment]
This is the single way to make the framework work well with pino. And I believe nestjs authors did not accidentally make that `message: any` in version 8 which adds support for other logger implementations to fit nest logger interface with their own types order

Please check the pino library interpolations, you can do something like `info({foo: "bar"}, `%s %o`, "baz", {qux: 42})`. How would you do that in not confusing nest-way? The only way is to accept args the same way as pino does. Any other way of changing args positions would be even more confusing and much more complex internally

**Comment by yamcodes** [comment]
I am working on a fork designed to be a drop-in replacement for NestJS's logger: [pino-nest.js.org](https://pino-nest.js.org/)

```ts
// With nestjs-pino (Pino style):
this.logger.log({ foo: 'bar' }, 'Hello World');

// With pino-nestjs (NestJS style):
this.logger.log('Hello World', { foo: 'bar' });
```
