### ISSUE TITLE
[FEATURE REQUEST] use "name" instead of "context" for the context

### ISSUE THREAD

**Issue by Nhacsam** [iamolegga/nestjs-pino#97]
**Is your feature request related to a problem? Please describe.**
I just migrated from another library I used to use `name: {ModuleName}` for the context.
The main reason I did choose this, is that the default key used by [pino-pretty](https://github.com/pinojs/pino-pretty)

I would like to change the context key to use `name` instead.

**Describe the solution you'd like**
I think it would be a good idea to have an extra option at the initialization to define the key used for the context.

**Describe alternatives you've considered**
I tried to implement it, but I didn't weel understood the typing of the options. So I don't know how to add the option.
My code is here : https://github.com/Nhacsam/nestjs-pino/tree/add-param-to-context-key

**Comment by iamolegga** [comment]
All right, got you. I'll try to find time for implementing this in next week or two

**Comment by Nhacsam** [comment]
Thank you @iamolegga

**Comment by StevenLangbroek** [comment]
Does #115 match your expectations? We have internally started using the `module` key but ecosystem interop is important for us.

**Comment by StevenLangbroek** [comment]
Ah sorry I missed the requirement on being able to set it at root level. Refactornig.

**Comment by iamolegga** [comment]
@StevenLangbroek answered you in related PR 🙂

**Comment by iamolegga** [comment]
done in v1.1.0

see [params](https://github.com/iamolegga/nestjs-pino#configuration-params) and [migration guide](https://github.com/iamolegga/nestjs-pino#migrating)

**Comment by Nhacsam** [comment]
Awesome, thanks !
