### ISSUE TITLE
This is not a platform agnostic logger

### ISSUE THREAD

**Issue by atassis** [iamolegga/nestjs-pino#973]
[X] I've read [the docs of nestjs-pino](https://github.com/iamolegga/nestjs-pino/blob/master/README.md)

[X] I've read [the docs of pino](https://getpino.io/#/)

[X] I couldn't find the same [open issue of nestjs-pino](https://github.com/iamolegga/nestjs-pino/issues)

**What is the current behavior?**
It uses the pino-http package
**What is the expected behavior?**
Pino-http is a package to serialize, log http request, though there are tons of different mechanisms to use for nestjs
**Please provide minimal example repo. Without it this issue will be closed**

**Please mention other relevant information such as Node.js version and Operating System.**

**Comment by atassis** [comment]
Okay, thats a dup of #803

**Comment by iamolegga** [comment]
@atassis platform here stands for `express` and `fastify` frameworks. If it doesn't fit your needs feel free to fork it or write your own from scratch.

**Comment by atassis** [comment]
Have already got the point from issue above, thanks
Made my own thingy
